return {
	leghrk = {
		buildpic = "LEGHRK.DDS",
		buildtime = 9000,
		canmove = true,
		collisionvolumeoffsets = "0 -2 0",
        collisionvolumescales = "40.0 40.0 46.0",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		energycost = 9000,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 6200,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.1265,
		maxdec = 0.6486,
		maxslope = 28,
		maxwaterdepth = 88,
		metalcost = 750,
		movementclass = "BOT3",
		separationDistance = 8,
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/LEGHRK.s3o",
		script = "Units/LEGHRK.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 1070.5,
		speed = 65,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.188,
		turnrate = 300,
		upright = false,
		customparams = {
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "legion/bots/T2 Bots",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 0.0 0.0",
				collisionvolumescales = "42.0 26.0 42.0",
				collisionvolumetype = "Box",
				damage = 450,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 194,
				object = "Units/leghrk_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 350,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 78,
				object = "Units/cor2X2B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			rocket_barrage = {
				areaofeffect = 296,
				avoidfeature = false,
				burst = 12,
				burstrate = 0.125,
				cegtag = "missiletrailtiny",
				craterboost = 0,
				cratermult = 0,
				dance = 24,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-small",
				firestarter = 70,
				flighttime = 4.9,
				impulsefactor = 2.123,
				metalpershot = 0,
				model = "legsmallrocket.s3o",
				movingaccuracy = 400,
				name = "CatapultRockets",
				noselfdamage = true,
				proximitypriority = -1,
				range = 1400,
				reloadtime = 9,
				smokecolor = 0.5,
				smokeperiod = 4,
				smokesize = 8.5,
				smoketime = 12,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "rockhit3",
				soundhitwet = "splssml",
				soundstart = "rockhvy3",
				startvelocity = 350,
				texture1 = "null",
				texture2 = "smoketrailbar",
				trajectoryheight = 2,
				turnrate = 400,
				turret = true,
				weaponacceleration = 220,
				weapontype = "MissileLauncher",
				weaponvelocity = 800,
				wobble = 1500,
				damage = {
					default = 250,
				},
				customparams = {
					projectile_destruction_method = "explode",
					overrange_distance = 1450,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "ROCKET_BARRAGE",
				maindir = "0 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
