return {
	leginfestor = {
		maxacc = 0.45,
		maxdec = 1.65,
		energycost = 5200,
		metalcost = 250,
		buildpic = "LEGINFESTOR.DDS",
		builddistance = 175,
		buildtime = 3000,
		builder = true,
		canassist = true,
		cancapture = true,
		cancloak = true,
		cloakcost = 10,
		canreclaim = true,
		canmove = true,
		capturespeed = 2100,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "32 30 32",
		collisionvolumetype = "Cyly",
		corpse = "DEAD",
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 95,
		idletime = 100,
		health = 9200,
		maxslope = 50,
		speed = 84.0,
		maxwaterdepth = 65,
		movementclass = "TBOT3",
		mygravity = 10000,
		nochasecategory = "VTOL",
		objectname = "Units/leginfestor.s3o",
		script = "Units/leginfestor.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 1200,
		strafetoattack = false,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.0626,
		turnrate = 1214.40002,
		workertime = 500,
		buildoptions = {
			[1] = "leginfestor"
			[2] = "legmine3"
		},
		customparams = {
			unitgroup = 'weapon',
			model_author = "Zath (model), Tuerk (animation)",
			normaltex = "unittextures/leg_normal.dds",
			paralyzemultiplier = 0.2,
			selectable_as_combat_unit = true,
			subfolder = "CorBots/T2",
			techlevel = 2,
			selectionscalemult = 1,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "30 20 30",
				collisionvolumetype = "CYLY",
				damage = 750,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 10,
				metal = 523,
				object = "Units/leginfestor_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1500,
				footprintx = 3,
				footprintz = 3,
				metal = 209,
				object = "Units/cor3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "spider2",
			},
			select = {
				[1] = "spider",
			},
		},
		weapondefs = {
			festorbeam = {
				areaofeffect = 82,
				avoidfeature = false,
				beamtime = 0.25,
				corethickness = 0.15,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:laserhit-small",
				firestarter = 90,
				impulsefactor = 0.99,
				laserflaresize = 1.95,
				name = "Close-Quarters Light Heat Ray",
				noselfdamage = true,
				projectiles = 5,
				sprayangle = 50,
				range = 1490,
				reloadtime = 1,
				rgbcolor = "1 0.25 0.44",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray1",
				soundtrigger = 1,
				thickness = 1.5,
				tolerance = 2000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1600,
				damage = {
					default = 120,
					subs = 95,
					vtol = 140,
				},
			},
		},
		weapons = {
			[1] = {
				def = "festorbeam",
				onlytargetcategory = "SURFACE VTOL",
				burstControlWhenOutOfArc = 1,
			},
		},
	},
}
