return {
	armsptkt4 = {
		maxacc = 0.207,
		maxdec = 0.6486,
		energycost = 75000,
		metalcost = 7500,
		buildpic = "scavengers/armsptkt4.DDS",
		buildtime = 75000,
		canmove = true,
		collisionvolumeoffsets = "0 -4 0",
		collisionvolumescales = "75 50 75",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "empblast",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 45,
		idletime = 600,
		mass = 5000,
		health = 94000,
		speed = 76.0,
		maxwaterdepth = 155,
		movementclass = "EPICALLTERRAIN",
		mygravity = 10000,
		nochasecategory = "VTOL",
		objectname = "Units/scavboss/armsptkt4.s3o",
		script = "Units/scavboss/armsptkt4.cob",
		seismicsignature = 0,
		selfdestructas = "empblast",
		sightdistance = 1100,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 350,
		turnrate = 650,
		customparams = {
			unitgroup = 'weapon',
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			paralyzemultiplier = 0.125,
			subfolder = "ArmBots/T2",
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.13973236084 -4.67773437585e-06 -1.37111663818",
				collisionvolumescales = "47.3038787842 18.2459106445 47.0814971924",
				collisionvolumetype = "Box",
				damage = 12500,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 40,
				metal = 3750,
				object = "Units/scavboss/armsptkt4_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 6250,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 1875,
				object = "Units/arm4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "spider2",
			},
			select = {
				[1] = "spider3",
			},
		},
		weapondefs = {
			adv_rocket = {
				areaofeffect = 390,
				avoidfeature = false,
				burst = 18,
				burstrate = 0.1,
				cegtag = "missiletrailsmall",
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				dance = 16,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 5,
				impulsefactor = 1.223,
				model = "catapultmissile.s3o",	--catapultmissile.s3o
				movingaccuracy = 450,
				name = "Parabolic trajectory g2g multi-rocket launcher",
				noselfdamage = true,
				range = 1599,
				reloadtime = 5,
				smoketrail = false,
				soundhit = "rockhit",
				soundhitwet = "splssml",
				soundstart = "rocksalvo",
				soundtrigger = true,
				startvelocity = 125,
				targetmoveerror = 0.2,
				texture1 = "null",
				texture2 = "smoketrailbar",
				trajectoryheight = 4,
				turnrate = 2000,
				turret = true,
				weaponacceleration = 195,
				weapontimer = 7,
				weapontype = "MissileLauncher",
				weaponvelocity = 1090,
				wobble = 2000,
				damage = {
					default = 1500,
					subs = 900,
				},
				customparams = {
					projectile_destruction_method = "descend",
					overrange_distance = 1790,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ADV_ROCKET",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
