return {
	armhawk = {
		airsightdistance = 2400,
		blocking = false,
		buildpic = "ARMHAWK.DDS",
		buildtime = 10500,
		canfly = true,
		canmove = true,
		collide = false,
		cruisealtitude = 660,
		energycost = 5700,
		explodeas = "smallExplosionGenericAir",
		footprintx = 2,
		footprintz = 2,
		health = 9370,
		maxacc = 0.4625,
		maxaileron = 0.01458,
		maxbank = 0.8,
		maxdec = 0.03025,
		maxelevator = 0.01083,
		maxpitch = 0.625,
		maxrudder = 0.00633,
		maxslope = 22,
		maxwaterdepth = 0,
		metalcost = 140,
		nochasecategory = "UNDERWATER",
		objectname = "Units/ARMHAWK.s3o",
		radardistance = 1600,
		script = "Units/ARMHAWK.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericAir",
		sightdistance = 1130,
		speed = 488.8,
		speedtofront = 0.063,
		stealth = true,
		turnradius = 64,
		usesmoothmesh = true,
		wingangle = 0.06333,
		wingdrag = 0.0575,
		customparams = {
			attacksafetydistance = 600,
			fighter = 1,
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmAircraft/T2",
			techlevel = 2,
			unitgroup = "aa",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-tiny",
				[2] = "crashing-tiny2",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			armvtol_advmissile = {
				areaofeffect = 528,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				canattackground = true,
				castshadow = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.45,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				firestarter = 0,
				flighttime = 5.5,
				impactonly = 1,
				impulsefactor = 0.46,
				metalpershot = 0,
				model = "cormissile.s3o",
				name = "High velocity a2a missile launcher",
				noselfdamage = true,
				range = 2090,
				reloadtime = 1.4,
				smokecolor = 0.65,
				smokeperiod = 8,
				smokesize = 2.8,
				smoketime = 16,
				smoketrail = false,
				smoketrailcastshadow = false,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				startvelocity = 233,
				texture1 = "null",
				texture2 = "smoketrail",
				tolerance = 8000,
				tracks = true,
				turnrate = 19000,
				weaponacceleration = 174,
				weapontimer = 3,
				weapontype = "MissileLauncher",
				weaponvelocity = 1270,
				damage = {
					commanders = 12,
					default = 324,
					vtol = 1100,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTAIR",
				def = "ARMVTOL_ADVMISSILE",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
