return {
	armdrone = {
		blocking = false,
		buildpic = "ARMKAM.DDS",
		buildtime = 1200,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 440,
		energycost = 600,
		explodeas = "smallExplosionGeneric",
		footprintx = 1,
		footprintz = 1,
		health = 3450,
		hoverattack = true,
		maxacc = 0.44,
		maxdec = 1.0,
		maxslope = 25,
		maxwaterdepth = 0,
		metalcost = 25,
		nochasecategory = "VTOL",
		objectname = "Units/ARMDRONE.s3o",
		script = "Units/ARMDRONE.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 900,
		speed = 530,
		turninplaceanglelimit = 360,
		turnrate = 1500,
		customparams = {
			drone = 1,
			model_author = "FireStorm",
			nohealthbars = 1,
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmAircraft",
			unitgroup = "weapon",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2",
				[2] = "airdeathceg3",
				[3] = "airdeathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			med_emg = {
				accuracy = 14,
				areaofeffect = 16,
				avoidfeature = false,
				burnblow = false,
				burst = 7,
				burstrate = 0.06,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.025,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:laserhit-small-yellow",
				impulsefactor = 0.91,
				intensity = 0.8,
				name = "Rapid-fire a2g machine guns",
				noselfdamage = true,
				ownerexpaccweight = 5,
				predictboost = 1,
				range = 1550,
				reloadtime = 1.8,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun3",
				sprayangle = 1024,
				thickness = 0.7,
				tolerance = 6000,
				turret = false,
				weapontype = "LaserCannon",
				weaponvelocity = 1100,
				customparams = {
					norangering = 1,
				},
				damage = {
					default = 11,
					vtol = 23,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "MED_EMG",
				maindir = "0 0 1",
				maxangledif = 100,
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
