return {
	crawl_blastsml = {
		areaofeffect = 500,
		craterboost = 0.4,
		cratermult = 0.2,
		edgeeffectiveness = 0.45,
		explosiongenerator = "custom:genericunitexplosion-large-dirty",
		impulsefactor = 0.988,
		name = "WimpyCrawlingBomb",
		range = 580,
		reloadtime = 1.6,
		soundhit = "xplolrg3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 450,
		damage = {
			commanders = 1000,
			crawlingbombs = 400,
			default = 22000,
		},
	},
	crawl_blast = {
		areaofeffect = 590,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.35,
		explosiongenerator = "custom:genericunitexplosion-huge-dirty",
		impulsefactor = 0.5,
		name = "CrawlingBomb",
		range = 450,
		reloadtime = 3.6,
		soundhit = "xplonuk3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 450,
		damage = {
			commanders = 1000,
			crawlingbombs = 400,
			default = 22720,
			hvyboats = 2670,
			lboats = 2670,
		},
	},
	crawl_blastxl = {
		areaofeffect = 632,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.35,
		explosiongenerator = "custom:genericunitexplosion-gigantic-dirty",
		impulsefactor = 3.5,
		name = "CrawlingBomb",
		range = 450,
		reloadtime = 3.6,
		soundhit = "xplonuk3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 1000,
			crawlingbombs = 400,
			default = 22710,
			hvyboats = 2670,
			lboats = 2670,
		},
	},
	crawl_blastsmlscavboss = {
		areaofeffect = 1500,
		craterareaofeffect = 1500,
		craterboost = 0.4,
		cratermult = 0.2,
		edgeeffectiveness = 0.25,
		explosiongenerator = "custom:newnukehuge",
		impulsefactor = 3,
		name = "HugeAssMegaNuke",
		range = 400,
		reloadtime = 3.6,
		soundhit = "xplomed4",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 560,
			default = 56100,
		},
	},
	fb_blastsml = {
		areaofeffect = 550,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.35,
		explosiongenerator = "custom:genericunitexplosion-medium-dirty",
		impulsefactor = 0,
		name = "WimpyFlyingBomb",
		range = 400,
		reloadtime = 3.6,
		soundhit = "xplomed4",
		soundstart = "largegun",
		soundstartvolume = 30,
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 220,
			default = 3440,
		},
	},
}
