return {
	leglrpc = {
		maxacc = 0,
		maxdec = 0,
		buildangle = 32700,
		energycost = 69000,
		metalcost = 4700,
		buildpic = "LEGLRPC.DDS",
		buildtime = 85000,
		canrepeat = false,
		--collisionvolumeoffsets = "0 0 -20",
		--collisionvolumescales = "48 90 48",
		--collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "hugeBuildingExplosionGeneric",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		health = 4450,
		maxslope = 25,
		maxwaterdepth = 0,
		objectname = "Units/LEGLRPC.s3o",
		script = "Units/LEGLRPC.cob",
		seismicsignature = 0,
		selfdestructas = "hugeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		--usepiececollisionvolumes = 1,
		yardmap = "oooooooooooooooo",
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/leglrpc_aoplane.dds",
			buildinggrounddecalsizey = 9,
			buildinggrounddecalsizex = 9,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'weapon',
			canareaattack = 1,
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removewait = true,
			subfolder = "Legion/Defenses",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "3.15924835205 -0.787798413086 6.6563873291",
				collisionvolumescales = "81.6838531494 113.772003174 72.5632324219",
				collisionvolumetype = "Box",
				damage = 2520,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 40,
				metal = 2720,
				object = "Units/leglrpc_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1260,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 1088,
				object = "Units/arm3X3E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servlrg3",
			},
			select = {
				[1] = "servlrg3",
			},
		},
		weapondefs = {
			lrpc = {
				accuracy = 350,
				areaofeffect = 257,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				burst = 3,
				burstrate = 0.77777,
				sprayangle = 25, --
				cegtag = "arty-extraheavy",
				collidefriendly = false,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.15,
				energypershot = 9000,
				explosiongenerator = "custom:genericshellexplosion-large-bomb",
				gravityaffected = "true",
				--hightrajectory = 1,
				--heightboostfactor = 10,
				impulsefactor = 2.1,
				mygravity = 0.12,
				name = "Heavy Long-Range Plasma Bombardment Cannon",
				noselfdamage = true,
				range = 6400,
				reloadtime = 18,
				rgbcolor = "0.9, 0.55, 0",
				soundhit = "rflrpcexplo",
				soundhitvolume = 42,
				soundhitwet = "splshbig",
				soundstart = "lrpcshot",
				turret = true,
				weapontimer = 14,
				trajectoryheight = 2,
				--weaponacceleration = 325,
				weapontype = "Cannon",
				weaponvelocity = 1200,
				--projectiles = 3,
				--wobble = 0,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 5,
				},
				
				damage = {
					default = 1000,
					shields = 500,
					subs = 600,
					vtol = 1225,
				},
				--damage = {
					--default = 500,
					--shields = 250,
					--subs = 200,
				--},
			},
			cluster_munition = {
				areaofeffect = 295,
				avoidfeature = false,
				cegtag = "arty-extraheavy",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.73,
				explosiongenerator = "custom:genericshellexplosion-large-bomb", -- "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulsefactor = 4.25,
				name = "Plasma Cluster Burst", --"Plasma Burst",
				noselfdamage = true,
				maxvelocity = 520,
				range = 100,
				rgbcolor = "0.9 0.7 0.12",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				weapontype = "Cannon",
				damage = {
					default = 450,
					lboats = 400,
					subs = 425,
					vtol = 1195,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "LRPC",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
