return {
	leglrpc = {
		maxacc = 0,
		maxdec = 0,
		buildangle = 32700,
		energycost = 76000,
		metalcost = 5200,
		buildpic = "LEGLRPC.DDS",
		buildtime = 93000,
		canrepeat = false,
		--collisionvolumeoffsets = "0 0 -20",
		--collisionvolumescales = "48 90 48",
		--collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "hugeBuildingExplosionGeneric",
		footprintx = 5,
		footprintz = 5,
		health = 4450,
		maxslope = 25,
		maxwaterdepth = 0,
		objectname = "Units/LEGLRPC.s3o",
		script = "Units/LEGLRPC.cob",
		seismicsignature = 0,
		selfdestructas = "hugeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		--usepiececollisionvolumes = 1,
		yardmap = "oooooooooooooooo",
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/leglrpc_aoplane.dds",
			buildinggrounddecalsizey = 9,
			buildinggrounddecalsizex = 9,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'weapon',
			canareaattack = 1,
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removewait = true,
			subfolder = "Legion/Defenses",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "3.15924835205 -0.787798413086 6.6563873291",
				collisionvolumescales = "81.6838531494 113.772003174 72.5632324219",
				collisionvolumetype = "Box",
				damage = 2520,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 40,
				metal = 2720,
				object = "Units/leglrpc_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1260,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 1088,
				object = "Units/arm3X3E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servlrg3",
			},
			select = {
				[1] = "servlrg3",
			},
		},
		weapondefs = {
			lrpc = {
				accuracy = 130,
				sprayangle = 130,
				areaofeffect = 535,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "starfire-small",
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				burst = 3,
				burstrate = 0.4,
				edgeeffectiveness = 0.15,
				energypershot = 6000,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				heightboostfactor = 8,
				hightrajectory = 1, -- addedd
				impulseboost = 2.1, -- addedd
				impulsefactor = 5.5,
				leadbonus = 0,
				model = "legbomb.s3o",
				name = "Long-Range g2g Heavy Cluster Plasma Cannon",
				noselfdamage = true,
				projectiles = 1,
				range = 6100, --4800
				reloadtime = 18,
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundhitvolume = 38,
				soundstartvolume = 24,
				stockpile = true,
				stockpiletime = 5,
				sprayangle = 250,
				trajectoryhight = 2, -- addedd
				tolerance = 11220, -- addedd
				turnrate = 6700, -- addedd
				turret = true,
				weaponacceleration = 250, -- addedd
				weapontimer = 3.3,
				weapontype = "StarburstLauncher",
				weaponvelocity = 700,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 9,
					stockpilelimit = 3,
				},
				damage = {
					default = 600,
					shields = 300,
					subs = 120,
					vtol = 725,
				},
			},
			
			cluster_munition = {
				areaofeffect = 315,
				avoidfeature = false,
				burnblow = true,
				cegtag = "ministarfire",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:ministarfire-explosion",
				flighttime = 0.4,
				gravityaffected = "true", -- 
				mygravity = 0.01,
				hightrajectory = 1, -- addedd
				impulseboost = 2.1, -- addedd
				impulsefactor = 2.24,
				name = "Plasma Burst",
				noselfdamage = true,
				maxvelocity = 70,
				range = 240,
				rgbcolor = "0.8 0.8 1.0",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				weapontype = "Cannon",
				damage = {
					default = 100,
					lboats = 100,
					subs = 25,
					vtol = 325,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "LRPC",
				onlytargetcategory = "SURFACE",
			},
			
			[2] = {
				badtargetcategory = "MOBILE",
				def = "CLUSTER_MUNITION",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
