return {
	leglht = {
		airsightdistance = 1050,
		maxacc = 0,
		maxdec = 0,
		buildangle = 32000,
		energycost = 550,
		metalcost = 70,
		buildpic = "LEGLHT.DDS",
		buildtime = 2200,
		canrepeat = false,
		cantbetransported = false,
		collisionvolumeoffsets = "0 -7 0",
		collisionvolumescales = "32 61 32",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "mediumBuildingExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		mass = 5100,
		health = 2150,--650
		maxslope = 28,
		maxwaterdepth = 0,
		nochasecategory = "MOBILE",
		objectname = "Units/LEGLHT.s3o",
		script = "Units/LEGLHT.cob",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 894,
		yardmap = "oooo",
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/leglht_aoplane.dds",
			buildinggrounddecalsizey = 5,
			buildinggrounddecalsizex = 5,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'weapon',
			basename = "base",
			cannon1name = "barrel",
			driftratio = "0.6",
			firingceg = "barrelshot-tiny",
			flare1name = "flare",
			kickback = "-2.0",
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removewait = true,
			subfolder = "CorBuildings/LandDefenceOffence",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -7 0",
				collisionvolumescales = "32 61 32",
				collisionvolumetype = "CylY",
				damage = 351,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 55,
				object = "Units/LEGLHT_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 176,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 22,
				object = "Units/cor2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "lltok",
			},
			select = {
				[1] = "lltselect",
			},
		},
		weapondefs = {
			starfire = {
				accuracy = 1,
				areaofeffect = 156,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				burst = 3,
				burstrate = 0.01,
				highTrajectory = 1,
				cegtag = "starfire",
				collidefriendly = false,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.95,
				energypershot = 36,
				fireTolerance = 364,
				tolerance = 364,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				impulsefactor = 2.5,
				name = "Starfire Barrage Launcher",
				noselfdamage = true,
				range = 1389,
				reloadtime = 0.3,
				rgbcolor = "0.7 0.7 1.0",
				sprayangle = 30,
				soundhit = "rflrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot",
				soundhitvolume = 26,
				turret = true,
				weapontimer = 0.3,
				weapontype = "Cannon",
				weaponvelocity = 600,
				damage = {
					commanders = 270,
					default = 200,
					vtol = 250,
				},
				customparams = {
					exclude_preaim = true
				}
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "starfire",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
