return {
	legrhapsis = {
		maxacc = 0,
		airsightdistance = 850,
		maxdec = 0,
		buildangle = 8192,
		energycost = 6500,
		metalcost = 280,
		buildpic = "LEGRHAPSIS.DDS",
		buildtime = 4700,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "28 40 28",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energyupkeep = 5,
		explodeas = "mediumBuildingexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		health = 2900, --1900
		maxslope = 28,
		maxwaterdepth = 0,
		objectname = "Units/LEGRHAPSIS.s3o",
		script = "Units/LEGRHAPSIS.cob",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 975,
		yardmap = "ooooooooo",
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/legrhapsis_aoplane.dds",
			buildinggrounddecalsizey = 5,
			buildinggrounddecalsizex = 5,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'aa',
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removewait = true,
			subfolder = "Legion/Defenses",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "28 40 28",
				collisionvolumetype = "CylY",
				damage = 1500,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 10,
				metal = 190,
				object = "Units/legrhapsis_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 750,
				footprintx = 3,
				footprintz = 3,
				metal = 100,
				object = "Units/cor2X2C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "twrturn3",
			},
			select = {
				[1] = "twrturn3",
			},
		},
		weapondefs = {
			cor_advsam = {
				areaofeffect = 435,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				canattackground = false,
				cegtag = "missiletrailaa-large",
				collidefriendly = false,
				craterareaofeffect = 435,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.75,
				energypershot = 1800,
				explosiongenerator = "custom:genericshellexplosion-huge-aa",
				firestarter = 90,
				flighttime = 2.2,
				impulsefactor = 2.11,
				metalpershot = 0,
				model = "corscreamermissile.s3o",
				name = "Long-range heavy g2a missile launcher",
				noselfdamage = true,
				projectiles = 1, --1
				proximitypriority = -1,
				range = 2400,
				reloadtime = 1.8,
				smoketrail = true,
				smokePeriod = 3,
				smoketime = 24,
				smokesize = 11,
				smokecolor = 0.9,
				smokeTrailCastShadow = false,
				castshadow = false,
				soundhit = "impact",
				soundhitwet = "splslrg",
				soundstart = "aarocket",
				soundhitvolume = 8,
				soundstartvolume = 8,
				sprayangle = 10000,
				startvelocity = 1400,
				stockpile = true,
				stockpiletime = 4,
				texture1 = "null",
				texture2 = "smoketrailaaflak",
				tolerance = 10000,
				tracks = true,
				trajectoryheight = 1, -- 0.55
				turnrate = 99000,
				turret = true,
				weaponacceleration = 1000,
				weapontype = "MissileLauncher",
				weaponvelocity = 1850,
				--customparams = {
				--	stockpilelimit = 10,
				--},
				damage = {
					default = 500, --10
					vtol = 550, --750
				},
			},
		},
		weapons = {
			[1] = {
				--badtargetcategory = "NOTAIR",
				def = "COR_ADVSAM",
				onlytargetcategory = "VTOL SURFACE",
				fastautoretargeting = true,
			},
		},
	},
}
