return {
	legdrone = {
		maxacc = 0.95,
		blocking = false,
		maxdec = 2.05,
		energycost = 500,
		metalcost = 15,
		buildpic = "legdrone.DDS",
		buildtime = 1000,
		canfly = true,
		canmove = true,
		cantbetransported = false,
		collide = true,
		cruisealtitude = 908,
		explodeas = "tinyExplosionGeneric",
		footprintx = 1,
		footprintz = 1,
		hoverattack = true,
		idleautoheal = 0,
		idletime = 1800,
		health = 3915,
		maxslope = 25,
		speed = 430.5,
		maxwaterdepth = 0,
		nochasecategory = "COMMANDER VTOL",
		objectname = "Units/LEGDRONE.s3o",
		repairable = false,
		script = "Units/LEGDRONE.cob",
		seismicsignature = 0,
		selfdestructas = "tinyExplosionGenericSelfd",
		sightdistance = 1400,
		turninplaceanglelimit = 360,
		turnrate = 2400,
		upright = true,
		usesmoothmesh = 0,
		customparams = {
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "CorAircraft",
			drone = 1,
			nohealthbars = 1,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			semiauto = {
				accuracy = 7,
				areaofeffect = 316,
				avoidfeature = false,
				burst = 9,
				burstrate = 0.066,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.09,
				edgeeffectiveness = 0.55,
				explosiongenerator = "custom:plasmahit-sparkonly",
				impulsefactor = 1.123,
				intensity = 0.8,
				name = "Burst-fire Machine Gun",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 1290,
				reloadtime = 1.8,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun3",
				soundtrigger = true,
				sprayangle = 1024,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3.0,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 992,
				damage = {
					default = 32,
					vtol = 24,
				},
			},
		},
		weapons = {
			[1] = {
				--badtargetcategory = "VTOL",
				def = "SEMIAUTO",
				maindir = "0 0 1",
				maxangledif = 180,
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
