return {
	legkam = {
		acceleration = 0.6,
		blocking = false,
		maxdec = 0.1,
		energycost = 2000,
		metalcost = 65,
		buildpic = "LEGKAM.DDS",
		buildtime = 2200,
		canfly = true,
		canmove = true,
		collide = false,
		collisionvolumeoffsets = "0 5 12",
		collisionvolumescales = "15 15 40",
		collisionvolumetype = "CylZ",
		cruisealtitude = 990,
		explodeas = "tinyExplosionGeneric",
		firestate = 0,
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 45,
		idletime = 100,
		maxacc = 2.2,
		maxaileron = 0.028,
		maxbank = 0.8,
		health = 160,
		maxelevator = 0.01,
		maxpitch = 0.625,
		maxrudder = 0.015,
		maxslope = 22,
		speed = 430.0,
		maxwaterdepth = 0,
		nochasecategory = "VTOL",
		objectname = "Units/legkam.s3o",
		script = "Units/legkam.cob",
		seismicsignature = 0,
		selfdestructas = "",
		selfdestructcountdown = 0,
		sightdistance = 1130,
		speedtofront = 0.06183,
		turnradius = 48,
		turnrate = 1000,
		usesmoothmesh = true,
		wingangle = 0.06296,
		wingdrag = 0.06,
		customparams = {
			unitgroup = 'weapon',
			model_author = "Protar",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Air",
			crashable = 0,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:genericunitexplosion-large",
			},
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2",
				[2] = "airdeathceg3",
				[3] = "airdeathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			trigger = {
				areaofeffect = 40,
				avoidfeature = false,
				burst = 12,
				burstrate = 0.5,
				collidefriendly = 0,
				commandfire = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				impulsefactor = 0.788,
				model = "legnade.s3o",
				mygravity = 0.23,
				name = "Martyr trigger",
				range = 1410,
				reloadtime = 10,
				weapontype = "AircraftBomb",
				customparams = {
				},
				damage = {
					default = 10,
				},
			},
			crawl_detonator = {
				areaofeffect = 510,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.45,
				explosiongenerator = "",
				firesubmersed = true,
				gravityaffected = "true",
				impulsefactor = 1.3,
				name = "Mine Detonator",
				range = 55,
				reloadtime = 0.5,
				soundhit = "bombdropxx",
				soundhitwet = "splshbig",
				soundstart = "bombdropxx",
				weapontype = "Cannon",
				weaponvelocity = 1000,
				damage = {
					vtol = 2000,
					default = 1500,
				},
			},
			martyrbomb = {
				areaofeffect = 500,
				avoidfeature = false,
				collidefriendly = 0,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.35,
				explosiongenerator = "custom:genericunitexplosion-medium-dirty",
				impulsefactor = 1,
				metalpershot = 500,
				model = "Units/legkam.s3o",
				mygravity = 0.2,
				name = "Crawlingbomb Dummy Weapon",
				range = 1400,
				reloadtime = 10,
				soundhit = "xplomed4",
				soundhitwet = "sizzle",
				soundstart = "bombdropxx",
				weapontype = "AircraftBomb",
				customparams = {
					spawns_name = "legvision",
					spawns_surface = "LAND SEA",
					spawns_expire = 10,
				},
				damage = {
					commanders = 330,
					default = 440,
				},
			},
		},
		weapons = {
			[1] = {
				def = "TRIGGER",
				maindir = "0 -1 1",
				maxangledif = 150,
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "CRAWL_DETONATOR",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				def = "MARTYRBOMB",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
