return {
	armart = {
		buildpic = "armart.DDS",
		buildtime = 3000,
		canmove = true,
		collisionvolumeoffsets = "0 0 -5",
		collisionvolumescales = "30 24 35",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 2200,
		explodeas = "smallexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 2420,
		hightrajectory = 1,
		leavetracks = true,
		maxacc = 0.06727,
		maxdec = 0.15454,
		maxslope = 25,
		maxwaterdepth = 33,
		metalcost = 135,
		movementclass = "TANK3",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/armart.s3o",
		script = "Units/armart.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 864,
		speed = 81,
		trackoffset = 6,
		trackstrength = 5,
		tracktype = "armpincer_tracks",
		trackwidth = 30,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.29228,
		turnrate = 393.79999,
		customparams = {
			basename = "base",
			canareaattack = 1,
			kickback = "-6.25",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmVehicles",
			unitgroup = "weapon",
			weapon1turretx = 40,
			weapon1turrety = 110,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 3.10058593911e-07 3.44650268555",
				collisionvolumescales = "30.6000061035 17.1577606201 39.1929931641",
				collisionvolumetype = "Box",
				damage = 418,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 24,
				metal = 92,
				object = "Units/armart_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 259,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 37,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tnkt1artyok",
			},
			select = {
				[1] = "tnkt1artysel",
			},
		},
		weapondefs = {
			tawf113_weapon = {
				accuracy = 215,
				areaofeffect = 75,
				avoidfeature = false,
				cegtag = "arty-small",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.35,
				explosiongenerator = "custom:genericshellexplosion-small-bomb",
				gravityaffected = "true",
				hightrajectory = 1,
				impulsefactor = 1.91,
				mygravity = 0.276, -- 0.276
				name = "Long-range high-trajectory g2g plasma cannon",
				noselfdamage = true,
				projectiles = 3, --
				sprayangle = 205,
				range = 1420,
				reloadtime = 4.3,
				soundhit = "tawf113a",
				soundhitwet = "splsmed",
				soundstart = "cannhvy3",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				damage = {
					default = 99,
					subs = 61,
					vtol = 120,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "TAWF113_WEAPON",
				maindir = "0 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
