return {
	arm_superpawn = {
		buildpic = "ARMPW.DDS",
		buildtime = 1650,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "22 30 22",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		-- energycost = 900,
		explodeas = "smallExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
        health = 25000,                -- Massive health pool (Default is much lower)
        metalCost = 500,              -- Increase cost for balance
        energyCost = 4000,
		maxacc = 0.814,
		maxdec = 1.4,
		maxslope = 39,
		maxwaterdepth = 144,
		-- metalcost = 54,
		movementclass = "BOT2",
		nochasecategory = "VTOL",
		objectname = "Units/ARMPW.s3o",
		script = "Units/ARMPW.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 1129,
		speed = 167,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.22,
		turnrate = 1544,
		upright = true,
		customparams = {
			model_author = "Kaiser",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots",
			unitgroup = "weapon",
			weapon1turretx = 400,
			weapon1turrety = 400,
		    i18n_en_humanname ="Super Pawn",      -- The name displayed in-game
			i18n_en_tooltip = "Heavy Assault Bot", -- The unit tooltip description
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.979118347168 -0.453806965332 -0.796119689941",
				collisionvolumescales = "30.1392364502 18.4953460693 29.797164917",
				collisionvolumetype = "Box",
				damage = 192,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 40,
				metal = 29,
				object = "Units/armpw_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 96,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 12,
				object = "Units/arm2X2F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servtny2",
			},
			select = {
				[1] = "servtny2",
			},
		},
		weapondefs = {
			heavy_plasma_shotgun = {
				areaofeffect = 448,
				avoidfeature = false,
				burst = 3,
				burstrate = 0.6,
				craterareaofeffect = 125,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:plasmahit-small",
				firestarter = 100,
				flighttime = 3.1,
				gravityaffected = "true",
				impulsefactor = 4.23,
				intensity = 0.2,
				name = "Rapid-fire close-quarters g2g plasma guns",
				noselfdamage = true,
				projectiles = 5, --
				range = 1800,
				reloadtime = 3.1,
				rgbcolor = "1 0.95 0.45",
				size = 1.25,
				soundhitwet = "splshbig",
				soundstart = "flashemg",
				sprayangle = 780,
				tolerance = 10000,
				trajectoryheight = 2,
				turret = true,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 9,
					vtol = 15,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "Heavy_Plasma_Shotgun",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
