return {
	armflea = {
		buildpic = "ARMFLEA.DDS",
		buildtime = 800,
		canmove = true,
		category = "GROUNDSCOUT",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "20 12 20",
		collisionvolumetype = "cylY",
		corpse = "DEAD",
		energycost = 300,
		explodeas = "tinyexplosiongeneric",
		footprintx = 1,
		footprintz = 1,
		health = 960,
		maxacc = 0.575,
		maxdec = 1.725,
		maxslope = 255,
		maxwaterdepth = 55,
		metalcost = 21,
		movementclass = "SBOT2",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/ARMFLEA.s3o",
		script = "Units/ARMFLEA.cob",
		seismicsignature = 0,
		selfdestructas = "tinyexplosiongenericSelfd",
		sightdistance = 900,
		speed = 172,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.904,
		turnrate = 1807,
		customparams = {
			model_author = "Kaiser",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots",
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.00276184082031 -0.139985849609 -0.0299072265625",
				collisionvolumescales = "18.3164367676 15.4085083008 17.7548828125",
				collisionvolumetype = "Box",
				damage = 30,
				featuredead = "HEAP",
				footprintx = 1,
				footprintz = 1,
				height = 20,
				metal = 9,
				object = "Units/armflea_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "21.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 15,
				footprintx = 1,
				footprintz = 1,
				height = 4,
				metal = 4,
				object = "Units/arm1X1A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servtny2",
			},
			select = {
				[1] = "servtny2",
			},
		},
		weapondefs = {
			flea_laser = {
				areaofeffect = 22,
				avoidfeature = false,
				beamtime = 0.1,
				beamttl = 1,
				burstrate = 0.2,
				corethickness = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:laserhit-tiny-yellow",
				firestarter = 50,
				impactonly = 1,
				impulsefactor = 0.005,
				laserflaresize = 0.65,
				name = "Light Close-Quarters Fast-Firing g2g Laser",
				noselfdamage = true,
				projectiles = 5, --
				range = 540,
				reloadtime = 0.6,
				rgbcolor = "1 0.95 0.4",
				rgbcolor2 = "1 0.55 0.3",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrfir1",
				soundtrigger = 1,
				sprayangle = 190,
				thickness = 0.2,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 600,
				damage = {
					default = 24,
					vtol = 20,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "FLEA_LASER",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
