return {
	armmh = {
		airsightdistance = 1760,
		buildpic = "ARMMH.DDS",
		buildtime = 3300,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "33 26 43",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 3000,
		explodeas = "mediumexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 8530,
		maxacc = 0.15561,
		maxdec = 0.15561,
		maxslope = 33,
		maxwaterdepth = 0,
		metalcost = 175,
		movementclass = "HOVER3",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/ARMMH.s3o",
		radardistance = 1290,
		radaremitheight = 72,
		script = "Units/ARMMH.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 1109,
		speed = 143.9,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.5972,
		turnrate = 570,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmHovercraft",
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0 -2 0",
				collisionvolumescales = "33 15 43",
				collisionvolumetype = "Box",
				damage = 286,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				metal = 106,
				object = "Units/armmh_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 143,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 42,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-small-hover",
				[2] = "custom:bowsplash-small-hover",
				[3] = "custom:hover-wake-small",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovt1vrocok",
			},
			select = {
				[1] = "hovt1vrocsel",
			},
		},
		weapondefs = {
			armmh_weapon = {
				areaofeffect = 364,
				avoidfeature = false,
				burnblow = true,
				burst = 3,
				burstrate = 3,
				castshadow = true,
				cegtag = "missiletrailsmall-starburst",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 100,
				flighttime = 24,
				impulsefactor = 2.65,
				metalpershot = 0,
				model = "corkbmissl1.s3o",
				name = "Light long-range g2g starburst rocket launcher",
				noselfdamage = true,
				range = 1680,
				reloadtime = 15,
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 10,
				smoketime = 28,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplomed4",
				soundhitwet = "splssml",
				soundstart = "Rockhvy1",
				sprayangle = 190,
				texture1 = "null",
				texture2 = "smoketrailbar",
				texture3 = "null",
				tolerance = 4000,
				tracks = true,
				turnrate = 8000,
				weaponacceleration = 120,
				weapontimer = 4.5,
				weapontype = "StarburstLauncher",
				weaponvelocity = 1200,
				customparams = {
					overrange_distance = 1850,
					projectile_destruction_method = "descend",
					speceffect = "retarget",
				},
				damage = {
					default = 390,
					subs = 190,
					vtol = 950,
				},
			},
		},
		weapons = {
			[1] = {
				-- badtargetcategory = "MOBILE",
				def = "ARMMH_WEAPON",
				fastautoretargeting = true, --
				fastquerypointupdate = true, --
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
