return {
	armlwall = {
		maxacc = 0,
		energycost = 4800, --3x armclaw
		metalcost = 1020, --3x armclaw
		buildpic = "ARMLWALL.DDS",
		buildtime = 14000, --3x armclaw
		canrepeat = false,
		collisionvolumeoffsets = "0 -3 0",
		collisionvolumescales = "32 50 32",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		crushresistance = 1000,
		damagemodifier = 0.25,
		decoyfor = "armfort",
		explodeas = "smallBuildingexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		levelground = false,
		mass = 10000000000,
		health = 75320, --4x armclaw
		maxslope = 35,
		maxwaterdepth = 0,
		nochasecategory = "MOBILE",
		objectname = "Units/ARMLWALL.s3o",
		script = "Units/ARMLWALL.cob",
		seismicsignature = 0,
		selfdestructas = "tinyBuildingExplosionGenericSelfd",
		sightdistance = 630,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "ffff",
		customparams = {
			neutral_when_closed = true,
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/armfort_aoplane.dds",
			buildinggrounddecalsizey = 4,
			buildinggrounddecalsizex = 4,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'weapon',
			decoyfor = "armfort",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				autoreclaimable = 0,
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -3 0",
				collisionvolumescales = "32 50 32",
				collisionvolumetype = "CylY",
				damage = 540,
				featuredead = "ROCKTEETH",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 205,
				object = "Units/armfort.s3o",
				reclaimable = true,
			},
			rockteeth = {
				animating = 0,
				animtrans = 0,
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				crushresistance = 2500,
				damage = 5000,
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 2,
				object = "Units/arm1X1A.s3o",
				reclaimable = true,
				resurrectable = 0,
				shadtrans = 1,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-lightning",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3-lightning",
				[2] = "deathceg4-lightning",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servmed2",
			},
			select = {
				[1] = "servmed2",
			},
		},
		weapondefs = {
			lightning = {
				areaofeffect = 38,
				avoidfeature = false,
				beamttl = 1,
				burst = 10,
				burstrate = 0.03333,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 1,
				edgeeffectiveness = 0.15,
				energypershot = 5,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
				firestarter = 50,
				impactonly = 1,
				impulsefactor = 0.33,
				intensity = 22, --was 24
				name = "Medium Lightning Cannon",
				noselfdamage = true,
				paralyzer = true,
				paralyzetime = 2,
				range = 1215,
				reloadtime = 0.7777, --was 0.3333
				rgbcolor = "0.5 0.5 1",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				soundtrigger = true,
				thickness = 2.2, -- was 2.0
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 400,
				customparams = {
					exclude_preaim = true,
					spark_ceg = "genericshellexplosion-splash-lightning",
					spark_forkdamage = "0.83", --was 0.5
					spark_maxunits = "7", --2x armclaw
					spark_range = "180", --66% more than armclaw
				},
				damage = {
					default = 64, --1/2 of armthor | 2.66x armclaw
					vtol = 44,
				},
			},
			-- banisher = {
			-- 	areaofeffect = 128,
			-- 	avoidfeature = false,
			-- 	burnblow = true,
			-- 	burst = 5,
			-- 	burstrate = 0.5,
			-- 	cegtag = "missiletraillarge-red",
			-- 	craterareaofeffect = 128,
			-- 	craterboost = 0,
			-- 	cratermult = 0,
			-- 	edgeeffectiveness = 0.55,
			-- 	explosiongenerator = "custom:genericshellexplosion-large-bomb",
			-- 	firestarter = 20,
			-- 	flighttime = 7.4,
			-- 	impulseboost = 0.123,
			-- 	impulsefactor = 0.123,
			-- 	model = "banishermissile.s3o",
			-- 	name = "Banisher",
			-- 	noselfdamage = true,
			-- 	range = 800,
			-- 	reloadtime = 7.5,
			-- 	smoketrail = true,
			-- 	smokePeriod = 7, --7
			-- 	smoketime = 24, --48
			-- 	smokesize = 11.3,
			-- 	smokecolor = 0.82,
			-- 	smokeTrailCastShadow = false,
			-- 	soundhit = "corban_b",
			-- 	soundhitwet = "splsmed",
			-- 	soundstart = "corban_a",
			-- 	startvelocity = 240,
			-- 	texture1 = "null",
			-- 	texture2 = "railguntrail",
			-- 	tolerance = 9000,
			-- 	tracks = true,
			-- 	trajectoryheight = 0.45,
			-- 	turnrate = 30000,
			-- 	turret = true,
			-- 	weaponacceleration = 220,
			-- 	weapontimer = 0.25,
			-- 	weapontype = "StarburstLauncher",
			-- 	weaponvelocity = 650,
			-- 	damage = {
			-- 		commanders = 1000,
			-- 		default = 1000,
			-- 		subs = 500,
			-- 	},
			-- },
		},
		weapons = {
			[1] = {
				def = "lightning",
				onlytargetcategory = "NOTSUB SURFACE", -- SURFACE
				fastautoretargeting = true,
			},
		},
	},
}
