return {
	leghelios = {
		maxacc = 0.2,
		maxdec = 0.4,
		energycost = 2400,
		metalcost = 160,
		buildpic = "LEGHELIOS.DDS",
		buildtime = 2600,
		canmove = true,
		collisionvolumeoffsets = "0 -4 1",
		collisionvolumescales = "30 12 28",
		collisionvolumetype = "Box",
		usepiececollisionvolumes = 1,
		corpse = "DEAD",
		explodeas = "smallexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		leavetracks = true,
		health = 3500,
		maxslope = 25,
		speed = 100.0,
		maxwaterdepth = 55,
		movementclass = "TANK3",
		nochasecategory = "VTOL",
		objectname = "Units/LEGHELIOS.s3o",
		script = "Units/LEGHELIOS.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 860,
		trackoffset = 14,
		trackstrength = 5,
		tracktype = "corwidetracks",
		trackwidth = 28,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.96,
		turnrate = 500,
		customparams = {
			unitgroup = 'weapon',
			basename = "base",
			cannon1name = "barrel",
			driftratio = "0.6",
			firingceg = "barrelshot-tiny",
			flare1name = "flare",
			kickback = "-2.0",
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			restoretime = "3000",
			rockstrength = "0",
			sleevename = "turret",
			subfolder = "CorVehicles",
			turretname = "turret",
			wpn1turretx = 192.5,
			wpn1turrety = 192.5,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -4 1",
				collisionvolumescales = "30 12 28",
				collisionvolumetype = "Box",
				damage = 550,
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 105,
				object = "Units/leghelios_dead.s3o",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 225,
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 45,
				object = "units/cor2x2f.s3o",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tcormove",
			},
			select = {
				[1] = "tcorsel",
			},
		},
		weapondefs = {
			heat_ray = {
				accuracy = 90,
				areaofeffect = 24,
				avoidfeature = false,
				beamtime = 0.1, -- 0.5
				burst = 3,
				burstrate = 0.2,
				corethickness = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.067, --
				edgeeffectiveness = 0.45,
				explosiongenerator = "custom:laserhit-small",
				firestarter = 30,
				-- impactonly = 1,
				impulsefactor = 0.95,
				laserflaresize = 3,
				leadlimit = 0,
				name = "Light g2g Heat Ray",
				noselfdamage = true,
				predictboost = 1,
				projectiles = 5,
				sprayangle = 128,
				range = 1530,
				reloadtime = 1.3,
				-- rgbcolor = "1 0.8 0",
				-- rgbcolor2 = "0.8 0 0",
				rgbcolor = "1 0.55 0.07",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heliosfire",
				soundtrigger = 1,
				thickness = 1.0,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1950,
				damage = {
					default = 160,
					vtol = 225,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "HEAT_RAY",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
