return {
	leghades = {
		maxacc = 0.06788,
		maxdec = 0.13575,
		energycost = 800,
		metalcost = 65,
		buildpic = "LEGHADES.DDS",
		buildtime = 1600,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "16 10 23",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		explodeas = "smallExplosionGeneric",
		footprintx = 1,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		health = 925,
		maxslope = 22,
		speed = 152.0,
		maxwaterdepth = 44,
		movementclass = "TANK2",
		name = "Hades",
		nochasecategory = "VTOL",
		objectname = "Units/LEGHADES.s3o",
		script = "Units/LEGHADES.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 600,
		trackoffset = 5,
		trackstrength = 4,
		tracktype = "armpincer_tracks",
		trackwidth = 22,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.424,
		turnrate = 644,
		customparams = {
			unitgroup = 'weapon',
			basename = "base",
			firingceg = "barrelshot-tiny",
			kickback = "-2",
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "ArmVehicles",
			weapon1turretx = 240,
			weapon1turrety = 240,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -1 0",
				collisionvolumescales = "16 10 23",
				collisionvolumetype = "Box",
				damage = 250,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 40,
				object = "Units/leghades_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 193,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 20,
				object = "Units/arm2X2C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "veht1emgok",
			},
			select = {
				[1] = "veht1emgsel",
			},
		},
		weapondefs = {
			gauss = {
				areaofeffect = 88,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.05,
				explosiongenerator = "custom:genericshellexplosion-small",
				impactonly = 1,
				impulsefactor = 0.723,
				name = "Close-quarters g2g gauss-cannon",
				noselfdamage = true,
				predictboost = 1,
				range = 810,
				reloadtime = 2.25,
				size = 3,
				soundhit = "xplomed1",
				soundhitwet = "splsmed",
				soundstart = "cannhvy1",
				soundstartvolume = 2,
				--sprayangle = 500,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 650,
				damage = {
					default = 75,
					vtol = 25,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "GAUSS",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
