return {
	legavrad = {
		activatewhenbuilt = true,
		buildpic = "LEGAVRAD.DDS",
		buildtime = 7290,
		canattack = false,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "35 36 33",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 2000,
		explodeas = "smallexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 980,
		leavetracks = true,
		maxacc = 0.04878,
		maxdec = 0.09757,
		maxslope = 16,
		maxwaterdepth = 0,
		metalcost = 125,
		movementclass = "TANK3",
		movestate = 0,
		objectname = "Units/LEGAVRAD.s3o",
		onoffable = false,
		radardistance = 2300,
		script = "Units/LEGAVRAD.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 900,
		speed = 57,
		trackoffset = 5,
		trackstrength = 5,
		tracktype = "armseer_tracks",
		trackwidth = 24,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.33584,
		turnrate = 605,
		customparams = {
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Vehicles/T2 Vehicles",
			shield_color_mult = 25,
			shield_power = 49400,
			shield_radius = 710,
			techlevel = 2,
			unitgroup = "util",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -4 0",
				collisionvolumescales = "28 30 34",
				collisionvolumetype = "Box",
				damage = 700,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 80,
				object = "Units/legavrad_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 500,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 48,
				object = "Units/arm3X3E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:radarpulse_t2",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "varmmove",
			},
			select = {
				[1] = "avradsel",
			},
		},
		
		weapondefs = {
			repulsor = {
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				name = "PlasmaRepulsor",
				range = 710,
				soundhitwet = "sizzle",
				weapontype = "Shield",
				damage = {
					default = 100,
				},
				shield = {
					alpha = 0.17,
					armortype = "shields",
					exterior = true,
					energyupkeep = 0,
					force = 2.5,
					intercepttype = 1015,
					power = 49400,
					powerregen = 520,
					powerregenenergy = 2250,
					radius = 710,
					repulser = false,
					smart = true,
					startingpower = 15438,
					visiblerepulse = true,
					badcolor = {
						[1] = 1,
						[2] = 0.2,
						[3] = 0.2,
						[4] = 0.2,
					},
					goodcolor = {
						[1] = 0.2,
						[2] = 1,
						[3] = 0.2,
						[4] = 0.17,
					},
				},
			},
		},
		
		weapons = {
			[1] = {
				def = "REPULSOR",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
