return {
	legvcarry	= {
		maxacc = 0.04,
		maxdec = 0.08,
		energycost = 9000,
		metalcost = 400,
		buildpic = "LEGVCARRY.DDS",
		buildtime = 9000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "55 37 67",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		explodeas = "smallExplosionGeneric",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		health = 9400,
		maxslope = 25,
		speed = 68.0,
		maxwaterdepth = 44,
		movementclass = "HTANK4",
		name = "Mantis",
		nochasecategory = "VTOL",
		objectname = "Units/LEGVCARRY.s3o",
		script = "Units/LEGVCARRY.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 900,
		trackoffset = 6,
		trackstrength = 6,
		tracktype = "armstump_tracks",
		trackwidth = 56,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.952,
		turnrate = 460,
		customparams = {
			unitgroup = 'weapon',
			basename = "base",
			firingceg = "barrelshot-small",
			kickback = "-2.4",
			lumamult = "1.2",
			model_author = "ZephyrSkies (model), Johnathan Crimson (concept)",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Vehicles/T2 Vehicles",
			weapon1turretx = 45,
			weapon1turrety = 80,
			inheritxpratemultiplier = 1,
			childreninheritxp = "DRONE",
			parentsinheritxp = "DRONE",
			disable_when_no_air = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "55 37 67",
				collisionvolumetype = "Box",
				damage = 1056,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 210,
				object = "Units/legvcarry_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 528,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 80,
				object = "Units/arm2X2D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tnkt1canok",
			},
			select = {
				[1] = "tnkt1cansel",
			},
		},
		weapondefs = {
			targeting = {
				areaofeffect = 94,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				gravityaffected = "true",
				hightrajectory = 1,
				impulsefactor = 0.123,
				name = "Drone Targeting System",
				noselfdamage = true,
				metalpershot = 15,
				energypershot = 500,
				range = 1100,
				reloadtime = 2.5,
				size = 0,
				soundhit = "",
				soundhitwet = "",
				soundstart = "",
				stockpile = true,
				stockpiletime = 10,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				damage = {
					default = 0,
				},
				customparams = {
					carried_unit = "legdrone",     --Name of the unit spawned by this carrier unit.
					engagementrange = 1200,
					spawns_surface = "LAND",    -- "LAND" or "SEA". The SEA option has not been tested currently.
					spawnrate = 10, 				--Spawnrate roughly in seconds.
					maxunits = 16,				--Will spawn units until this amount has been reached.
					energycost = 500,			--Custom spawn cost. Remove this or set = nil to inherit the cost from the carried_unit unitDef. Cost inheritance is currently not working.
					metalcost = 15,				--Custom spawn cost. Remove this or set = nil to inherit the cost from the carried_unit unitDef. Cost inheritance is currently not working.
					controlradius = 1200,			--The spawned units should stay within this radius. Unfinished behavior may cause exceptions. Planned: radius = 0 to disable radius limit.
					decayrate = 4,
					carrierdeaththroe = "release",
					dockingarmor = 0.2,
					dockinghealrate = 86,
					docktohealthreshold = 66,
					enabledocking = true,		--If enabled, docking behavior is used. Currently docking while moving or stopping, and undocking while attacking. Unfinished behavior may cause exceptions.
					dockingHelperSpeed = 5,
					dockingpieces = "8 10 12 14 16 18",
					dockingradius = 80,			--The range at which the units snap to the carrier unit when docking.
					stockpilelimit = 16,
					stockpilemetal = 15,
					stockpileenergy = 500,
					dronesusestockpile = true,
					cobdockparam = 1,
					cobundockparam = 1,
				}
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL", --
				def = "targeting",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
