return {
	leegmech = {
		maxacc = 0.21845,
		airsightdistance = 1400,
		maxdec = 1.4521,
		energycost = 200000,
		metalcost = 10000,
		buildpic = "LEGMECH.DDS",
		buildtime = 200000,
		canmove = true,
		collisionvolumeoffsets = "0 -11 0",
		collisionvolumescales = "66 86 66",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "bantha",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 85,
		idletime = 900,
		mass = 200000,
		health = 80000,
		maxslope = 28,
		speed = 60.5,
		maxwaterdepth = 44,
		movementclass = "HBOT4",
		nochasecategory = "VTOL",
		objectname = "Units/LEGMECH.s3o",
		script = "Units/LEGMECH.cob",
		seismicsignature = 0,
		selfdestructas = "banthaSelfd",
		selfdestructcountdown = 10,
		sightdistance = 917,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.089,
		turnrate = 450,
		upright = true,
		customparams = {
			unitgroup = 'weapon',
			customrange = 1400,
			model_author = "Kremenchuk",
			normaltex = "unittextures/leegmech_normal.dds",
			subfolder = "leggantry",
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "5 -2 0",
				collisionvolumescales = "73 24 87",
				collisionvolumetype = "Box",
				damage = 30000,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 6350,
				object = "Units/legmech_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 10500,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 3300,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small-impulse",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "krogok1",
			},
			select = {
				[1] = "krogsel1",
			},
		},
		weapondefs = {
			aimhull = {
				areaofeffect = 210,
				avoidfeature = false,
				burnblow = true,
				burst = 16,
				burstrate = 0.2,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:burnfire-xs",
				firestarter = 70,
				flighttime = 8,--4
				impulsefactor = 1.19,
				model = "artshell-large.s3o",
				name = "Parabolic trajectory g2g multi-rocket launcher",
				noselfdamage = true,
				range = 1100,
				reloadtime = 8,
				smoketrail = true,
				smokePeriod = 7,
				smoketime = 21,
				smokesize = 6.5,
				smokecolor = 0.5,
				smokeTrailCastShadow = false,
				castshadow = true, --projectile
				soundhitdry = "flamhit1",
				soundhitwet = "splssml",
				soundstart = "rocksalvo",
				soundtrigger = true,
				startvelocity = 160,
				targetmoveerror = 0.2,
				texture1 = "null",
				texture2 = "smoketraildark",
				trajectoryheight = 1.5,
				turnrate = 6000,
				turret = true,
				weaponacceleration = 120,
				weapontimer = 6,
				weapontype = "MissileLauncher",
				weaponvelocity = 620,--600
				wobble = 10000,
				customparams = {
					area_onhit_ceg = "fire-area-75-repeat",
					area_onhit_damageCeg = "burnflamexl-gen",
					area_onhit_resistance = "fire",
					area_onhit_damage = 40,
					area_onhit_range = 125,
					area_onhit_time = 25,
					overrange_distance = 1230,
					projectile_destruction_method = "descend",
				},
				damage = {
					default = 40,
					subs = 15,
				},
			},
			shotgun = {
				areaofeffect = 150,
				avoidfeature = false,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-small",
				impulsefactor = 1.82,
				intensity = 2,
				name = "Shotgun",
				noselfdamage = true,
				predictboost = 1,
				projectiles = 12,
				range = 1050,
				reloadtime = 3,
				rgbcolor = "1 0.75 0.25",
				size = 2,
				soundhit = "xplomed2xs",
				soundhitwet = "splsmed",
				soundstart = "kroggie2xs",
				soundstartvolume = 12,
				sprayangle = 1400,--1500
				tolerance = 6000,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 800,--600
				damage = {
					default = 125,
				},
			},
			railgunt3 = {
				areaofeffect = 24,
				avoidfeature = false,
				burnblow = true,
				cegtag = "railgun",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 1000,
				explosiongenerator = "custom:plasmahit-sparkonly",
				firestarter = 0,
				hardstop = true,
				impactonly = true,
				impulsefactor = 3.11,
				intensity = 0.8,
				name = "Railgun",
				noexplode = true,
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 1050,
				reloadtime = 2.25,
				rgbcolor = "0.74 0.64 0.94",
				soundhit = "mavgun3",
				soundhitwet = "splshbig",
				soundstart = "railgun3",
				soundstartvolume = 26,
				thickness = 3,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 3180,
				customparams = {
					overpenetrate = true,
				},
				damage = {
					commanders = 250,
					default = 500,
				},
			},
			frontgun = {
				accuracy = 7,
				areaofeffect = 36,
				avoidfeature = false,
				burst = 7,--4
				burstrate = 0.07,--0.0675
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.04,--0.04
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.02,
				firestarter = 0,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Rapid-fire short range machine guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 780,
				reloadtime = 0.4,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundstartvolume = 7.5,
				sprayangle = 968,
				thickness = 1.4,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 921,
				damage = {
					commanders = 44,
					default = 44,
					vtol = 44,
				},
			},
			topgunaa = {
				accuracy = 7,
				areaofeffect = 96,
				avoidfeature = false,
				burst = 5,
				burstrate = 0.1,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.055,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.02,
				firestarter = 0,
				impulsefactor = 2.15,
				intensity = 0.8,
				name = "Rapid-fire anti-air machine guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 1257,
				reloadtime = 0.88,--1
				rgbcolor = "1 0.4 0.95",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundstartvolume = 12,
				sprayangle = 1000,
				thickness = 1.1,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 975,
				damage = {
					default = 95,
				},
			},
		},
		weapons = {
			[1] = {
				def = "AIMHULL",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				--badtargetcategory = "VTOL",
				def = "SHOTGUN",
				maindir = "1 0 0",
				maxangledif = 270,
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				def = "RAILGUNT3",
				maindir = "-1 0 0",
				maxangledif = 270,
				onlytargetcategory = "NOTSUB",
			},
			[4] = {
				badtargetcategory = "VTOL",
				def = "FRONTGUN",
				maindir = "0 0 1",
				maxangledif = 270,
				onlytargetcategory = "SURFACE",
			},
			[5] = {
				badtargetcategory = "NOTAIR GROUNDSCOUT",
				def = "TOPGUNAA",
				onlytargetcategory = "VTOL",
			},
		},
	},
}
