return {
	legehovertank = {
		activatewhenbuilt = true,
		builder = false,
		buildpic = "legehovertank.DDS",
		buildtime = 33000,
        collisionvolumescales = "63 32 63",
        collisionvolumeoffsets = "0 -15 0",
        collisionvolumetype = "cylY",
		usepiececollisionvolumes = 1,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		cantbetransported = true,
		corpse = "dead",
		energycost = 25000,
		explodeas = "largeexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 22900,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.022,--0.01788,
		maxdec = 0.022,--0.01788,
		maxslope = 16,
		maxwaterdepth = 0,
		metalcost = 1350,
		movementclass = "HHOVER4",
		nochasecategory = "VTOL",
		objectname = "Units/legehovertank.s3o",
		radardistance = 0,
		script = "Units/legehovertank.cob",
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 1200,
		sonardistance = 1550,
		speed = 63,--47.5,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.122,
		turnrate = 300,--200,
		customparams = {
			model_author = "Gabs/ShadowsAIT & ZephyrSkies (Model), Protar (Concept Art)",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/T3",
			techlevel = 3,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				damage = 7000,
                collisionvolumescales = "63 22 62",
                collisionvolumetype = "cylY",
				featuredead = "heap",
				footprintx = 4,
				footprintz = 4,
				height = 15,
				metal = 514,
				object = "Units/legehovertank_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 3500,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 188,
				object = "Units/arm4x4d.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
				[2] = "custom:waterwake-small-hover",
				[3] = "custom:bowsplash-small-hover",
				[4] = "custom:hover-wake-large",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovt2lasok",
			},
			select = {
				[1] = "hovt2lassel",
			},
		},
		weapondefs = {
			heat_ray = {
				areaofeffect = 94,
				avoidfeature = false,
				avoidfriendly = true,
				beamtime = 0.033,
				corethickness = 0.5,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				energypershot = 300,
				explosiongenerator = "custom:heatray-large",
				firestarter = 30,
				firetolerance = 5000,
				impulsefactor = 0.0125,
				laserflaresize = 6,
				name = "Heavy Sweepfire Heatray",
				noselfdamage = true,
				predictboost = 0.5,
				proximitypriority = 1,
				range = 925,
				reloadtime = 3,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.8 1.0 0.3",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 11,
				soundtrigger = 1,
				tolerance = 5000,
				thickness = 4.0,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 950,
				damage = {
					default = 75,
					vtol = 117,
				},
				customparams = {
					sweepfire=9,--multiplier for displayed dps during the 'bonus' sweepfire stage, needed for DPS calcs
				}
			},
			depthcharge = {
				areaofeffect = 324,
				avoidfeature = false,
				avoidfriendly = false,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.9,
				explosiongenerator = "custom:genericshellexplosion-medium-uw",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "legbasictorpedo.s3o",
				name = "Depthcharge Launcher",
				noselfdamage = true,
				predictboost = 0,
				range = 1100,
				reloadtime = 2,
				soundhit = "xplodep2",
				soundstart = "torpedo1",
				startvelocity = 150,
				tolerance = 1000,
				tracks = true,
				turnrate = 6000,
				turret = true,
				waterweapon = true,
				weaponacceleration = 80,
				weapontimer = 3,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 240,
				damage = {
					default = 625,
				},
			},
			parabolic_rockets = {
				areaofeffect = 200,
				avoidfeature = false,
				--burnblow = true,
				burst = 4,
				burstrate = 0.25,
				castshadow = true,
				cegtag = "missiletrailsmall-simple",
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				dance = 48,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 4,
				impulsefactor = 1.06,
				model = "legsmallrocket.s3o",
				name = "Parabolic Trajectory Multi-Rocket Launcher",
				noselfdamage = true,
                proximitypriority = -1,
				range = 1200,
				reloadtime = 5,
				smokecolor = 0.5,
				smokeperiod = 7,
				smokesize = 6.5,
				smoketime = 21,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "rockhit",
				soundhitwet = "splssml",
				soundstart = "rocksalvo",
				soundtrigger = true,
				startvelocity = 215,
				targetmoveerror = 0.2,
				texture1 = "null",
				texture2 = "smoketrailbar",
				trajectoryheight = 0.66,
				turnrate = 8500,
				turret = true,
				weaponacceleration = 150,
				weapontimer = 0.75,
				weapontype = "MissileLauncher",
				weaponvelocity = 750,
				wobble = 12000,
				trajectoryheight = 1,
				fixedLauncher = true,
				fireTolerance = 11000,
				customparams = {
					--cruise_max_height = "20",
					--cruise_min_height = "15",
					--lockon_dist = "150",
					--speceffect = "cruise",
					projectile_destruction_method = "descend",
					overrange_distance = 1290,
				},
				damage = {
					default = 300,
					subs = 250,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "HEAT_RAY",
				onlytargetcategory = "SURFACE",
				fastautoretargeting = true,
				burstControlWhenOutOfArc = 2,
			},
			[2] = {
				badtargetcategory = "NOTSUB", -- NOTSUB
				def = "DEPTHCHARGE",
				maindir = "0 -1 0",
				maxangledif = 210,
				onlytargetcategory = "CANBEUW UNDERWATER",
			},
			[3] = {
				badtargetcategory = "VTOL",
				def = "parabolic_rockets",
				onlytargetcategory = "SURFACE",
				maindir = "0 0 1",
				maxangledif = 110,
			},
			[4] = {
				badtargetcategory = "VTOL",
				def = "parabolic_rockets",
				onlytargetcategory = "SURFACE",
				maindir = "0 0 1",
				maxangledif = 110,
			},
		},
	},
}
