return {
	armfark = {
		autoheal = 85,
		builddistance = 1136,
		builder = true,
		buildpic = "ARMFARK.DDS",
		buildtime = 4300,
		canmove = true,
		collisionvolumeoffsets = "0 0 -1",
		collisionvolumescales = "21 26 17",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 3000,
		energymake = 33,
		energystorage = 250,
		explodeas = "smallbuilder",
		footprintx = 2,
		footprintz = 2,
		health = 1235,
		idleautoheal = 25,
		idletime = 1800,
		maxacc = 0.4968,
		maxdec = 5.175,
		maxslope = 33,
		maxwaterdepth = 44,
		metalcost = 210,
		movementclass = "BOT3",
		objectname = "Units/ARMFARK.s3o",
		radardistance = 450,
		script = "Units/ARMFARK.cob",
		seismicsignature = 0,
		selfdestructas = "smallbuilderSelfd",
		sightdistance = 877,
		speed = 175,
		terraformspeed = 1900,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.7424,
		turnrate = 1265,
		upright = true,
		workertime = 540,
		buildoptions = {
			[1] = "armsolar",
			[2] = "armwin",
			[3] = "armmex",
			[4] = "armmakr",
			[5] = "armeyes",
			[6] = "armmark",
			[7] = "armaser",
		},
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "buildert2",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "21 5 17",
				collisionvolumetype = "Box",
				damage = 250,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 131,
				object = "Units/armfark_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 150,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 52,
				object = "Units/arm2X2D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
	},
}
