return {
	armmav = {
		autoheal = 50,
		buildpic = "ARMMAV.DDS",
		buildtime = 17000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "36 48 36",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 11000,
		explodeas = "mediumExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		health = 2560,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.138,
		maxdec = 0.43125,
		maxslope = 22,
		maxwaterdepth = 22,
		metalcost = 650,
		movementclass = "BOT4",
		nochasecategory = "VTOL",
		objectname = "Units/ARMMAV.s3o",
		script = "Units/ARMMAV.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 850,
		speed = 119.5,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.089,
		turnrate = 1285.69995,
		upright = true,
		customparams = {
			model_author = "Flaka",
			normaltex = "unittextures/Arm_normal.dds",
			rangexpscale = 0.6,
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "50.6378936768 10.4806671143 38.4813079834",
				collisionvolumetype = "Box",
				damage = 900,
				featuredead = "heap",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 394,
				object = "Units/armmav_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 696,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 196,
				object = "Units/arm2x2e.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small-impulse",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "mavbok1",
			},
			select = {
				[1] = "mavbsel1",
			},
		},
		weapondefs = {
			armmav_weapon = {
				alphadecay = 0.1,
				areaofeffect = 68,
				avoidfeature = false,
				cegtag = "impulse-trail",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-small",
				impactonly = 1,
				impulsefactor = 1.667,
				name = "Anti-swarm g2g gauss-impulse guns",
				nogap = false,
				noselfdamage = true,
				predictboost = 0.3,
				range = 865,
				reloadtime = 0.667,
				separation = 1,
				sizedecay = 0.01,
				soundhit = "xplomed5",
				soundhitwet = "splshbig",
				soundstart = "mavgun4",
				stages = 12,
				tolerance = 4000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 465,
					vtol = 165,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMMAV_WEAPON",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
