return {
	armsptk = {
		buildpic = "ARMSPTK.DDS",
		buildtime = 11500,
		canmove = true,
		collisionvolumeoffsets = "0 -2 0",
		collisionvolumescales = "42 28 42",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 4500,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 1390,
		maxacc = 0.407,
		maxdec = 1.2486,
		maxwaterdepth = 55,
		metalcost = 400,
		movementclass = "TBOT3",
		mygravity = 10000,
		nochasecategory = "VTOL",
		objectname = "Units/ARMSPTK.s3o",
		script = "Units/ARMSPTK.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 440,
		speed = 71,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.1352,
		turnrate = 1290,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			paralyzemultiplier = 0.2,
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.13973236084 -4.67773437585e-06 -1.37111663818",
				collisionvolumescales = "47.3038787842 18.2459106445 47.0814971924",
				collisionvolumetype = "Box",
				damage = 800,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 40,
				metal = 244,
				object = "Units/armsptk_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 500,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 98,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "spider2",
			},
			select = {
				[1] = "spider3",
			},
		},
		weapondefs = {
			adv_rocket = {
				areaofeffect = 120,
				avoidfeature = false,
				burst = 3,
				burstrate = 0.3,
				castshadow = true,
				cegtag = "missiletrailsmall-simple",
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-small-bomb",
				firestarter = 70,
				flighttime = 4.5,
				impulsefactor = 0.93,
				model = "cormissile2.s3o",
				name = "Parabolic trajectory g2g multi-rocket launcher",
				noselfdamage = true,
				range = 1175,
				reloadtime = 3.75,
				smokecolor = 0.5,
				smokeperiod = 7,
				smokesize = 6.5,
				smoketime = 21,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "rockhit3",
				soundhitwet = "splssml",
				soundstart = "rocksalvo",
				soundtrigger = true,
				startvelocity = 80,
				targetmoveerror = 0.2,
				texture1 = "null",
				texture2 = "smoketrailbar",
				trajectoryheight = 0.65,
				turnrate = 8000,
				turret = true,
				weaponacceleration = 100,
				weapontimer = 6,
				weapontype = "MissileLauncher",
				weaponvelocity = 650,
				wobble = 2500,
				customparams = {
					cruise_max_height = "150",
					cruise_min_height = "35",
					lockon_dist = "150",
					overrange_distance = 1270,
					projectile_destruction_method = "descend",
					speceffect = "cruise",
				},
				damage = {
					default = 200,
					subs = 100,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ADV_ROCKET",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "ADV_ROCKET",
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
		},
	},
}
