return {
	armvader = {
		activatewhenbuilt = true,
		buildpic = "ARMVADER.DDS",
		buildtime = 8000,
		canmove = true,
		cloakcost = 22,
		collisionvolumeoffsets = "0 2 0",
		collisionvolumescales = "17 13 17",
		collisionvolumetype = "box",
		corpse = "CORPSE",
		energycost = 12800,
		explodeas = "crawl_blast",
		firestate = 0,
		footprintx = 2,
		footprintz = 2,
		health = 25445,
		mass = 749,
		maxacc = 0.6018,
		maxdec = 2.0589,
		maxslope = 99,
		maxwaterdepth = 399,
		metalcost = 265,
		mincloakdistance = 580, --
		movementclass = "ABOTBOMB2",
		nochasecategory = "VTOL",
		objectname = "Units/ARMVADER.s3o",
		script = "Units/ARMVADER.cob",
		seismicsignature = 4,
		selfdestructas = "crawl_blast",
		selfdestructcountdown = 0,
		sightdistance = 673,
		speed = 134,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.848,
		turnrate = 3471,
		customparams = {
			instantselfd = true,
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "explo",
		},
		featuredefs = {
			corpse = {
				blocking = true,
				category = "corpses",
				damage = 300,
				featuredead = "HEAP",
				footprintx = 1,
				footprintz = 1,
				height = 20,
				metal = 49,
				object = "Units/armvader_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "21.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 200,
				footprintx = 1,
				footprintz = 1,
				height = 4,
				metal = 12,
				object = "Units/arm1X1B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servsml5",
			},
			select = {
				[1] = "servsml5",
			},
		},
		weapondefs = {
			crawl_detonator = {
				areaofeffect = 5,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				firesubmersed = true,
				gravityaffected = "true",
				impulsefactor = 0,
				name = "Self-destruction",
				range = 42,
				reloadtime = 0.1,
				soundhitwet = "splshbig",
				weapontype = "Cannon",
				weaponvelocity = 1000,
				damage = {
					crawlingbombs = 100,
					default = 33000,
				},
			},
			crawl_dummy = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidground = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 128,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				firesubmersed = true,
				impulsefactor = 0,
				name = "Crawlingbomb Dummy Weapon",
				range = 42,
				reloadtime = 0.1,
				soundhitwet = "sizzle",
				tolerance = 100000,
				waterweapon = true,
				weapontype = "Melee",
				weaponvelocity = 100000,
				customparams = {
					bogus = 1,
				},
				damage = {
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "CRAWL_DUMMY",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "CRAWL_DETONATOR",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
