return {
	armzeus = {
		buildpic = "ARMZEUS.DDS",
		buildtime = 7250,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "35 36 35",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 6100,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 8950,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.138,
		maxdec = 0.8625,
		maxslope = 85,
		maxwaterdepth = 33,
		metalcost = 350,
		movementclass = "BOT4",
		nochasecategory = "VTOL",
		objectname = "Units/ARMZEUS.s3o",
		script = "Units/ARMZEUS.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 831.5,
		speed = 97.4,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.0428,
		turnrate = 1214.40002,
		upright = true,
		customparams = {
			model_author = "FireStorm, FLaka",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "39.0425720215 11.3397369385 32.5729980469",
				collisionvolumetype = "Box",
				damage = 1300,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 214,
				object = "Units/armzeus_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 800,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 86,
				object = "Units/arm2X2E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-lightning",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg2",
				[4] = "deathceg3",
				[5] = "deathceg4-lightning",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			lightning = {
				areaofeffect = 48,
				avoidfeature = false,
				beamttl = 1,
				burst = 33,
				burstrate = 0.03333,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 1,
				edgeeffectiveness = 0.35,
				energypershot = 35,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
				firestarter = 50,
				impactonly = 1,
				impulsefactor = 0.222,
				intensity = 24,
				laserflaresize = 5,
				name = "Close-quarters g2g lightning rifle",
				noselfdamage = true,
				range = 680,
				reloadtime = 1.7,
				rgbcolor = "0.5 0.5 1",
				soundhit = "xplomed3",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				soundtrigger = true,
				thickness = 1.5,
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 400,
				customparams = {
					spark_ceg = "genericshellexplosion-splash-lightning",
					spark_forkdamage = "0.53",
					spark_maxunits = "5",
					spark_range = "120",
				},
				damage = {
					default = 52,
					vtol = 26,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTNING",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
