return {
	legatorpbomber = {
		blocking = false,
		buildpic = "LEGATORPBOMBER.DDS",
		buildtime = 18240,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 990,
		energycost = 9480,
		explodeas = "mediumexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 9900,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.3325,
		maxaileron = 0.01347,
		maxbank = 0.8,
		maxdec = 0.1725,
		maxelevator = 0.00972,
		maxpitch = 0.625,
		maxrudder = 0.00522,
		maxslope = 22,
		maxwaterdepth = 0,
		metalcost = 480,
		nochasecategory = "VTOL",
		objectname = "Units/LEGATORPBOMBER.s3o",
		radardistance = 1400,
		script = "Units/LEGATORPBOMBER.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 1200,
		sonardistance = 1790,
		speed = 410,
		speedtofront = 0.063,
		turnradius = 64,
		usesmoothmesh = true,
		wingangle = 0.06222,
		wingdrag = 0.18,
		customparams = {
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Air/T2 Air",
			techlevel = 2,
			unitgroup = "sub",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			legair_torp = {
				areaofeffect = 616,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				burst = 6,
				burstrate = 0.3,
				cegtag = "torpedotrail-large",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-large-uw",
				flighttime = 7,
				impulsefactor = 4.123,
				model = "legmediumtorpedo.s3o",
				mygravity = 0.2,
				name = "Medium Homing Torpedo Launcher",
				noselfdamage = true,
				range = 1700,
				reloadtime = 7,
				soundhit = "xplodep2",
				soundhitvolume = 3.5,
				soundhitwet = "splsmed",
				soundhitwetvolume = 14,
				soundstart = "bombrel",
				startvelocity = 195,
				tolerance = 2000,
				tracks = true,
				turnrate = 19000,
				turret = false,
				waterweapon = true,
				weaponacceleration = 235,
				weapontimer = 6,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 400,
				customparams = {
					speceffect = "torpwaterpen",
					norangering = 1,
				},
				damage = {
					default = 750,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTSHIP",
				def = "LEGAIR_TORP",
				onlytargetcategory = "NOTHOVER",
			},
			[2] = {
				badtargetcategory = "NOTSHIP",
				def = "LEGAIR_TORP",
				onlytargetcategory = "NOTHOVER",
			},
		},
	},
}
