return {
	legafigdef = {
		-- maxacc= 0.35,
		airsightdistance = 1800,
		blocking = false,
		maxdec = 0.0875,
		energycost = 8200,
		metalcost = 250,
		buildpic = "legafigdef.DDS",
		buildtime = 11850,
		canfly = true,
		canmove = true,
		collide = false,
		cruisealtitude = 800,
		explodeas = "smallExplosionGenericAir",
		footprintx = 2,
		footprintz = 2,
		maxacc= 0.44,
		maxaileron = 0.0165,
		maxbank = 0.725,
		health = 8480,
		maxelevator = 0.0135,
		maxpitch = 0.7455,
		maxrudder = 0.0155,
		maxslope = 25,
		speed = 270,
		maxwaterdepth = 0,
		nochasecategory = "UNDERWATER", --"NOTAIR",
		objectname = "Units/legafigdef.s3o",
		script = "Units/legafigdef.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericAir",
		sightdistance = 1230,
		speedtofront = 0.06475,
		stealth = false,
		turnradius = 32,
		turnrate = 1500,
		usesmoothmesh = true,
		wingangle = 0.06363,
		wingdrag = 0.21,
		customparams = {
			unitgroup = 'weapon',
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Air/T2 Air",
			techlevel = 2,
			attacksafetydistance = 800,
			fighter = 1,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-medium-aa",
			},
			crashexplosiongenerators = {
				[1] = "crashing-tiny",
				[2] = "crashing-tiny2",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			leggun = {
				accuracy = 5,
				areaofeffect = 35,
				avoidfeature = true,
				avoidfriendly = false,
				burst = 10,
				burstrate = 0.04,
				burnblow = false,
				collideFriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.05,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.0,
				firestarter = 50,
				impulsefactor = 1.5,
				impulseboost = 2.1,
				intensity = 0.8,
				minIntensity = 0.5,
				mygravity = 0.4,
				name = "Heavy A2A Gatling Guns",
				noselfdamage = true,
				ownerExpAccWeight = 8.0,
				predictboost = 1,
				proximitypriority = 1,
				range = 1780,
				reloadtime = 1,
				rgbcolor = "0.88 0.33 1",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundstartvolume = 2,
				soundTrigger = true,
				sprayangle = 155,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3.0,
				tolerance = 2400,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 2500,
				damage = {
					commanders = 1,
					default = 2,
					vtol = 80,
				},
				customparams = {
					noattackrangearc= 1,
				},
			},
			-- added
			armadvbomb = {
				areaofeffect = 768,
				avoidfeature = false,
				projectiles = 5,
				sprayangle = 445,
				burst = 7,
				burstrate = 0.2,
				collidefriendly = false,
				commandfire = false,
				craterareaofeffect = 168,
				craterboost = 1.1,
				cratermult = 1.1,
				edgeeffectiveness = 0.45,
				explosiongenerator = "custom:genericshellexplosion-large-bomb",
				gravityaffected = "true",
				impulsefactor = 7.33,
				impulseboost = 2.1,
				model = "airbombt2.s3o",
				mygravity = 0.4,
				name = "Heavy a2g impulse warheads",
				noselfdamage = true,
				range = 1780,
				reloadtime = 11,
				sprayangle = 1245,
				soundhit = "bombsmed2",
				soundhitwet = "splslrg",
				soundstart = "bombrelxl",
				weapontype = "AircraftBomb",
				damage = {
					default = 466,
					subs = 285,
				},
			}, 
		},
		
		weapons = {
			[1] = {
				--badtargetcategory = "NOTAIR",
				def = "leggun",
				maindir = "0 0 1",
				maxangledif = 28,
				onlytargetcategory = "VTOL NOTSUB SURFACE",
				weaponAimAdjustPriority = 30,
				fastAutoRetargeting = true,
			    },
			[2] = {
				badtargetcategory = "MOBILE",
				def = "ARMADVBOMB",
				onlytargetcategory = "NOTSUB SURFACE",
			    }, 
		},
	},
}