return {
	legmineb = {
		acceleration = 0.155,
		blocking = false,
		maxdec = 0.145,
		energycost = 21000,
		metalcost = 300,
		buildpic = "LEGMINEB.DDS",
		buildtime = 26000,
		canfly = true,
		canmove = true,
		collide = false,
		cruisealtitude = 1150,
		explodeas = "mediumExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.16,
		maxaileron = 0.01347,
		maxbank = 0.8,
		health = 1110,
		maxelevator = 0.00972,
		maxpitch = 0.625,
		maxrudder = 0.00522,
		maxslope = 22,
		speed = 310.0,
		maxwaterdepth = 0,
		noautofire = true,
		nochasecategory = "VTOL",
		objectname = "Units/legmineb.s3o",
		script = "Units/legmineb.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 1455,
		speedtofront = 0.07,
		turnradius = 64,
		turnrate = 800,
		usesmoothmesh = true,
		wingangle = 0.06222,
		wingdrag = 0.125,
		customparams = {
			unitgroup = 'weapon',
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Air/T2 Air",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2",
				[2] = "airdeathceg3",
				[3] = "airdeathceg4",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
		weapondefs = {
			cor_seaadvbomb = {
				accuracy = 400,
				areaofeffect = 540,
				avoidfeature = false,
				bounceexplosiongenerator = "custom:dirt",
				bouncerebound = 0.15,
				bounceslip = 0.75,
				burst = 12,
				burstrate = 0.25,
				collidefriendly = false,
				commandfire = false,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.85,
				metalpershot = 30,
				energypershot = 1620,
				explosiongenerator = "custom:dirtpopup",
				gravityaffected = "true",
				impulsefactor = 2.123,
				intensity = 0.01,
				model = "leglmineproj.s3o",
				mygravity = 0.14,
				name = "LegionMineBomb",
				noselfdamage = true,
				numbounce = 3,
				range = 2600,
				reloadtime = 10,
				rgbcolor = "0.8 0.8 0.25",
				size = 8,
				soundhitdry = "xplodragconcrete",
				soundhitwet = "splsmed",
				soundstart = "bombrel",
				sprayangle = 600,
				stockpile = true,
				stockpiletime = 10,
				waterbounce = true,
				weapontype = "AircraftBomb",
				customparams = {
					bogus = 1,
					spawns_name = "armmine3",
					spawns_surface = "LAND",
					stockpilelimit = 22,
				},
				damage = {
					default = 1,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COR_SEAADVBOMB",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
