return {
	armemp = {
		buildangle = 8192,
		buildpic = "ARMEMP.DDS",
		buildtime = 79300,
		collisionvolumeoffsets = "0 5 0",
		collisionvolumescales = "80 30 60",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 29000,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 3350,
		maxacc = 0,
		maxdec = 0,
		maxslope = 25,
		maxwaterdepth = 0,
		metalcost = 1600,
		objectname = "Units/ARMEMP.s3o",
		script = "Units/ARMEMP.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 455,
		yardmap = "oooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 6,
			buildinggrounddecalsizey = 6,
			buildinggrounddecaltype = "decals/armemp_aoplane.dds",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			techlevel = 2,
			unitgroup = "weapon",
			restrictions_inclusion = "_notacnukes_",
			usebuildinggrounddecal = true,
			-- yardmap = "ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "80 30 60",
				collisionvolumetype = "Box",
				damage = 1800,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 976,
				object = "Units/armemp_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 900,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 390,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servroc1",
			},
			select = {
				[1] = "servroc1",
			},
		},
		weapondefs = {
			armemp_weapon = {
				-- alwaysvisible = true,
				areaofeffect = 512,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "cruisemissiletrail-tacnuke",
				collideenemy = false,
				collidefeature = false,
				collidefriendly = false,
				commandfire = true,
				craterareaofeffect = 512,
				craterboost = 1.6,
				cratermult = 0.7,
				edgeeffectiveness = 0.55,
				energypershot = 17437,
				explosiongenerator = "custom:newnuketac",
				firestarter = 0,
				flighttime = 400,
				impulsefactor = 9.5,
				interceptedbyshieldtype = 0,
				metalpershot = 550,
				model = "cortronmissile.s3o",
				name = "Long range tactical g2g nuclear warheads",
				noselfdamage = true,
				range = 29999,
				reloadtime = 8,
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 20,
				smoketime = 63,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				startvelocity = 20,
				stockpile = true,
				stockpiletime = 65,
				trajectoryheight = 2
				texture1 = "flare2",
				turret = 1,
				texture2 = "smoketrailbar",
				texture3 = "null",
				tolerance = 4000,
				turnrate = 10000,
				weaponacceleration = 400,
				weapontimer = 3,
				weapontype = "MissileLauncher",
				weaponvelocity = 1500,
				wobble = 50,
				customparams = {
					cruise_max_height = "3520",
					cruise_min_height = "1830",
					lockon_dist = "1970",
					speceffect = "cruise",
					-- overrange_distance = 30000,
					projectile_destruction_method = "descend",
					shield_aoe_penetration = true,
					water_splash_ceg = "splash-gigantic", -- 1 bigger than it would get
					stockpilelimit = 10,
					nuclear = 1,
				},
				damage = {
					commanders = 500,
					scavboss = 10000,
					default = 2500,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTLAND",
				def = "ARMEMP_WEAPON",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
