return {
	armemp = {
		buildangle = 8192,
		buildpic = "ARMEMP.DDS",
		buildtime = 79300,
		collisionvolumeoffsets = "0 5 0",
		collisionvolumescales = "80 30 60",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 29000,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 3350,
		maxacc = 0,
		maxdec = 0,
		maxslope = 25,
		maxwaterdepth = 0,
		metalcost = 1600,
		objectname = "Units/ARMEMP.s3o",
		script = "Units/ARMEMP.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 455,
		yardmap = "oooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 6,
			buildinggrounddecalsizey = 6,
			buildinggrounddecaltype = "decals/armemp_aoplane.dds",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			techlevel = 2,
			unitgroup = "weapon",
			-- restrictions_inclusion = "_notacnukes_",
			usebuildinggrounddecal = true,
			yardmap = "ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "80 30 60",
				collisionvolumetype = "Box",
				damage = 1800,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 976,
				object = "Units/armemp_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 900,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 390,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servroc1",
			},
			select = {
				[1] = "servroc1",
			},
		},
		weapondefs = {
			armemp_weapon = {
				alwaysvisible = true,
				areaofeffect = 512,
				avoidfriendly = false,
				cegtag = "cruisemissiletrail-tacnuke",
				collidefriendly = 0,
				craterareaofeffect = 512,
				craterboost = 1.6,
				cratermult = 0.7,
				edgeeffectiveness = 0.45,
				explosiongenerator = "custom:newnuketac",
				firestarter = 100,
				flighttime = 100,
				impulsefactor = 0.5,
				interceptedbyshieldtype = 4,
				metalpershot = 0,
				model = "cortronmissile.s3o",
				name = "Long range tactical g2g nuclear warheads",
				range = 29999,
				reloadtime = 5,
				smoketrail = 1,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				startvelocity = 1,
				texture1 = "flare2",
				turret = 1,
				weaponacceleration = 1800,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 1500,
				wobble = 50,
				damage = {
					commanders = 500,
					scavboss = 10000,
					default = 2500,
				},
				customparams = {
					nuclear = 1,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "ARMEMP_WEAPON",
				-- onlytargetcategory = "EMPABLE NOTSUB",
			},
		},
	},
}
