return {
	armhlt = {
		airsightdistance = 2700,
		buildangle = 8192,
		buildpic = "ARMHLT.DDS",
		buildtime = 11300,
		canrepeat = false,
		collisionvolumeoffsets = "0 11 0",
		collisionvolumescales = "36 88 36",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 4700,
		explodeas = "mediumBuildingExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		health = 22600,
		maxacc = 0,
		maxdec = 0,
		maxslope = 25,
		maxwaterdepth = 0,
		metalcost = 440,
		nochasecategory = "MOBILE",
		objectname = "Units/ARMHLT.s3o",
		radardistance = 1600,
		-- radardistancejam = 950,
		radaremitheight = 72,
		script = "Units/ARMHLT.cob",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 1194,
		yardmap = "oooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 4,
			buildinggrounddecalsizey = 4,
			buildinggrounddecaltype = "decals/armhlt_aoplane.dds",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			unitgroup = "weapon",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "48 88 48",
				collisionvolumetype = "CYLY",
				damage = 1395,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 269,
				object = "Units/armhlt_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 698,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 108,
				object = "Units/arm2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "twractv3",
			},
			select = {
				[1] = "twractv3",
			},
		},
		weapondefs = {
			arm_laserh1 = {
				accuracy = 24,
				areaofeffect = 44,
				avoidfeature = true,
				avoidfriendly = false,
				beamtime = 0.1,
				burst = 4,
				burstrate = 0.2,
				corethickness = 0.25,
				burnblow = false,
				collideFriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.1, --
				edgeeffectiveness = 0.95,
				energypershot = 75,
				explosiongenerator = "custom:laserhit-large-green",
				firestarter = 90,
				-- impactonly = 1,
				impulsefactor = 1.84,
				intensity = 1.8, --
				laserflaresize = 5.5,
				name = "Heavy g2g high energy laser",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				predictboost = 0.5,
				proximitypriority = 1,
				range = 1750,
				reloadtime = 3.6,
				rgbcolor = "0 1 0.6",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun3",
				soundstartvolume = 3,
				soundTrigger = true,
				sprayangle = 200,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3.0,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon", --
				weaponvelocity = 2250,
				damage = {
					commanders = 380.5,
					default = 427,
					vtol = 390,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARM_LASERH1",
				fastautoretargeting = true,
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
