return {
	armllt = {
		buildangle = 32768,
		buildpic = "ARMLLT.DDS",
		buildtime = 2400,
		canrepeat = false,
		cantbetransported = false,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "32 77 32",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 680,
		explodeas = "mediumBuildingExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		health = 3520,
		mass = 5100,
		maxacc = 0,
		maxdec = 0,
		maxslope = 28,
		maxwaterdepth = 0,
		metalcost = 85,
		nochasecategory = "MOBILE",
		objectname = "Units/ARMLLT.s3o",
		radardistance = 1500,
		radaremitheight = 72,
		script = "Units/ARMLLT.cob",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 1094,
		sightemitheight = 72,
		yardmap = "oooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 4,
			buildinggrounddecalsizey = 4,
			buildinggrounddecaltype = "decals/armllt_aoplane.dds",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			unitgroup = "weapon",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -4 0",
				collisionvolumescales = "32 84 32",
				collisionvolumetype = "CylY",
				damage = 336,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 53,
				object = "Units/armllt_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 168,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 21,
				object = "Units/arm2X2B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "lltok",
			},
			select = {
				[1] = "lltselect",
			},
		},
		weapondefs = {
			heavy_plasma_shotgun = {
				areaofeffect = 298,
				avoidfeature = false,
				burst = 3,
				burstrate = 0.3,
				craterareaofeffect = 25,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.1,
				explosiongenerator = "custom:plasmahit-small",
				firestarter = 100,
				flighttime = 5.1,
				gravityaffected = "true",
				impulsefactor = 2.23,
				intensity = 0.2,
				name = "Rapid-fire close-quarters g2g plasma guns",
				noselfdamage = true,
				projectiles = 3, --
				range = 1800,
				reloadtime = 2.4,
				rgbcolor = "1 0.95 0.45",
				size = 0.35,
				soundhitwet = "splshbig",
				soundstart = "flashemg",
				sprayangle = 580,
				tolerance = 10000,
				trajectoryheight = 2,
				turret = true,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					default = 33,
					vtol = 65,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "Heavy_Plasma_Shotgun",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
