return {
	armsilo = {
		buildangle = 8192,
		buildpic = "ARMSILO.DDS",
		buildtime = 178500,
		collisionvolumeoffsets = "-1 3 1",
		collisionvolumescales = "90 80 90",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 90000,
		explodeas = "nukeBuilding",
		footprintx = 7,
		footprintz = 7,
		health = 5900,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 8100,
		objectname = "Units/ARMSILO.s3o",
		radardistance = 50,
		script = "Units/ARMSILO.cob",
		seismicsignature = 0,
		selfdestructas = "nukeBuildingSelfd",
		sightdistance = 455,
		yardmap = "ooooooooooooooooooooooooooooooooooooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 10,
			buildinggrounddecalsizey = 10,
			buildinggrounddecaltype = "decals/armsilo_aoplane.dds",
		    i18n_en_humanname ="BCB Nuke",      -- The name displayed in-game
			i18n_en_tooltip = "Hight Trajectory Nuclear warhead", -- The unit tooltip description
			model_author = "Cremuss",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			techlevel = 2,
			unitgroup = "nuke",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "90 80 90",
				collisionvolumetype = "CylY",
				damage = 3180,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 40,
				metal = 4956,
				object = "Units/armsilo_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1590,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 1982,
				object = "Units/arm3X3F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servroc1",
			},
			select = {
				[1] = "servroc1",
			},
		},
		weapondefs = {
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				gravityaffected = "true", --
				-- hightrajectory = 1,
				impulsefactor = 0,
				mygravity = 0.01, --
				maxvelocity = 1450, --
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				startvelocity = 585, --
				tolerance = 10000,
				turnrate = 100,
				weaponacceleration = 110,
				weapontimer = 0.05,
				weapontype = "Cannon",
				-- weaponvelocity = 1200,
				damage = {
					default = 0,
				},
			},
			nuclear_missile = {
				areaofeffect = 1400,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "NUKETRAIL",
				collideenemy = false,
				collidefeature = false,
				collidefriendly = false,
				commandfire = true,
				craterareaofeffect = 1400,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.45,
				energypershot = 125000,
				explosiongenerator = "custom:newnuke",
				firestarter = 100,
				flighttime = 300,
				gravityaffected = "true", --
				mygravity = 0.01, --
				impulseboost = 20,
				impulsefactor = 30,
				interceptedbyshieldtype = 0,
				metalpershot = 1000,
				model = "crblmssl.s3o",
				name = "Intercontinental ballistic nuclear warhead",
				range = 72000,
				reloadtime = 30,
				smokecolor = 0.85,
				smokeperiod = 10,
				smokesize = 28,
				smoketime = 130,
				smoketrail = true,
				smoketrailcastshadow = true,
				soundhit = "nukearm",
				soundhitwet = "nukewater",
				soundhitwetvolume = 53,
				soundstart = "nukelaunch",
				soundstartvolume = 20,
				startvelocity = 585, --
				stockpile = true,
				stockpiletime = 120,
				targetable = 1,
				texture1 = "null",
				texture2 = "railguntrail",
				texture3 = "null",
				tolerance = 4000, -- works
				turnrate = 3700, -- 
				weaponacceleration = 35,
				weapontimer = 4.5,
				weapontype = "StarburstLauncher",
				maxvelocity = 1620, --
				-- weaponvelocity = 3000,
				customparams = {
					place_target_on_ground = "true",
					shield_aoe_penetration = true,
					stockpilelimit = 10,
					nuclear = 1,
				},
				damage = {
					commanders = 2500,
					default = 119500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "NUCLEAR_MISSILE",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "NUCLEAR_LAUNCH",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
