return {
	armvulc = {
		buildangle = 29096,
		buildpic = "ARMVULC.DDS",
		buildtime = 1400000,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 -45",
		collisionvolumescales = "90 145 90",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 830000,
		explodeas = "customfusionexplo",
		firestate = 0,
		footprintx = 8,
		footprintz = 8,
		health = 32000,
		maxacc = 0,
		maxdec = 0,
		maxslope = 13,
		maxwaterdepth = 0,
		metalcost = 70000,
		objectname = "Units/ARMVULC.s3o",
		script = "Units/ARMVULC.cob",
		seismicsignature = 0,
		selfdestructas = "advancedFusionExplosionSelfd",
		sightdistance = 700,
		usepiececollisionvolumes = 1,
		yardmap = "oooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 7.5,
			buildinggrounddecalsizey = 7.5,
			buildinggrounddecaltype = "decals/armvulc_aoplane.dds",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			techlevel = 2,
			unitgroup = "weapon",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-30.100944519 -5.74996727295 19.3314819336",
				collisionvolumescales = "169.401870728 123.486465454 147.862945557",
				collisionvolumetype = "Box",
				damage = 26000,
				featuredead = "HEAP",
				footprintx = 7,
				footprintz = 7,
				height = 20,
				metal = 30000,
				object = "Units/armvulc_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 12000,
				footprintx = 7,
				footprintz = 7,
				height = 4,
				metal = 14000,
				object = "Units/arm7X7A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servlrg3",
			},
			select = {
				[1] = "servlrg3",
			},
		},
		weapondefs = {
			rflrpc = {
				accuracy = 700, --700
				areaofeffect = 485,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				castshadow = true,
				cegtag = "arty-huge",
				collidefriendly = false,
				craterboost = 0.1,
				cratermult = 0.1,
				craterareaofeffect = 480,
				edgeeffectiveness = 0.75,
				energypershot = 15000,
				explosiongenerator = "custom:genericshellexplosion-huge",
				model = "cormissile2.s3o",
				name = "Heavy long-range g2g ballistic missile launcher",
				flighttime = 45,
				gravityaffected = "true",
				-- hightrajectory = 1,
				impulsefactor = 7.77,
				-- name = "Rapid-fire long-range plasma cannon",
				noselfdamage = true,
				projectiles = 3, --
				range = 9050,
				reloadtime = 3,
				size = 7,
				-- rgbcolor = "1, 0.4, 0",
				smokecolor = 1,
				smokeperiod = 10,
				smokesize = 30,
				smoketime = 60,
				smoketrail = true,
				smoketrailcastshadow = true,
				soundhit = "rflrpcexplo",
				soundhitvolume = 39,
				soundhitwet = "splshbig",
				soundstart = "rocklit1",
				sprayangle = 895,
				-- startvelocity = 60,
				texture1 = "null",
				texture2 = "smoketrailbar",
				trajectoryheight = 2,
				tolerance = 10000,
				turnrate = 12000,
				turret = true,
				weaponacceleration = 20,
				weapontimer = 14,
				weapontype = "MissileLauncher",
				weaponvelocity = 1450,
				customparams = {
					cruise_max_height = "6000",
					cruise_min_height = "80",
					lockon_dist = "900",
					speceffect = "cruise",
					overrange_distance = 9200,
					projectile_destruction_method = "descend",
				},
				damage = {
					default = 825,
					shields = 412,
					subs = 250,
					vtol = 1150,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "RFLRPC",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
