return {
	armvulc = {
		buildangle = 29096,
		buildpic = "ARMVULC.DDS",
		buildtime = 1400000,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 -45",
		collisionvolumescales = "90 145 90",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 830000,
		explodeas = "customfusionexplo",
		firestate = 0,
		footprintx = 8,
		footprintz = 8,
		health = 32000,
		maxacc = 0,
		maxdec = 0,
		maxslope =22,
		maxwaterdepth = 0,
		metalcost = 70000,
		objectname = "Units/ARMVULC.s3o",
		script = "Units/ARMVULC.cob",
		seismicsignature = 0,
		selfdestructas = "advancedFusionExplosionSelfd",
		sightdistance = 700,
		usepiececollisionvolumes = 1,
		yardmap = "oooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 7.5,
			buildinggrounddecalsizey = 7.5,
			buildinggrounddecaltype = "decals/armvulc_aoplane.dds",
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removewait = true,
			subfolder = "ArmBuildings/LandDefenceOffence",
			techlevel = 2,
			unitgroup = "weapon",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-30.100944519 -5.74996727295 19.3314819336",
				collisionvolumescales = "169.401870728 123.486465454 147.862945557",
				collisionvolumetype = "Box",
				damage = 26000,
				featuredead = "HEAP",
				footprintx = 7,
				footprintz = 7,
				height = 20,
				metal = 30000,
				object = "Units/armvulc_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 12000,
				footprintx = 7,
				footprintz = 7,
				height = 4,
				metal = 14000,
				object = "Units/arm7X7A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servlrg3",
			},
			select = {
				[1] = "servlrg3",
			},
		},
		weapondefs = {
			rflrpc = {
				-- accuracy = 1000, --700
				areaofeffect = 592,
				avoidfeature = true,
				avoidfriendly = true,
				avoidground = false,
				bouncerebound = 0.22,
				bounceslip = 0.14,
				burnblow = true,
				canattackground = true,
				cegtag = "arty-huge",
				collidefriendly = false,
				craterareaofeffect = 382,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				energypershot = 15000,
				explosiongenerator = "custom:genericshellexplosion-huge",
				firetolerance = 5000,
				flighttime = 22.3,
				gravityaffected = "true",
				groundbounce = true,
				heightboostfactor = 9.8,
				hightrajectory = 1,
				trajectoryheight   = 1.1,
				impulsefactor = 9,
				--mygravity = 0.2,
				name = "Heavy long-range g2g plasma cannon",
				noselfdamage = true,
				numbounce = 2,
				projectiles = 3, --
				predictboost = 0.95,
				range = 8550,
				reloadtime = 3,
				separation = 2,
				size = 6,
				soundhit = "xplomed2",
				soundhitwet = "splslrg",
				soundstart = "cannhvy5",
				startvelocity = 490,
				sprayangle = 305,
				-- trajectoryheight = 2,
				turret = true,
				weaponacceleration = 130,
				weapontype = "Cannon",
				weaponvelocity = 850,
				damage = {
					default = 825,
					shields = 412,
					subs = 250,
					vtol = 1250,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "RFLRPC",
				onlytargetcategory = "SURFACE NOTAIR",
			},
		},
	},
}
