return {
	armlatnk = {
		airsightdistance = 7000,
		buildpic = "ARMLATNK.DDS",
		buildtime = 8000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "30 26 34",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 6400,
		explodeas = "smallExplosionGeneric",
		footprintx = 3,
		footprintz = 4,
		health = 25360,
		leavetracks = true,
		maxacc = 0.05833,
		maxdec = 0.11666,
		maxslope = 33,
		maxwaterdepth = 55,
		metalcost = 330,
		movementclass = "TANK3",
		nochasecategory = "VTOL",
		objectname = "Units/ARMLATNK.s3o",
		script = "Units/ARMLATNK.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 990,
		speed = 120,
		trackoffset = 6,
		trackstrength = 5,
		tracktype = "armacv_tracks",
		trackwidth = 36,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.19516,
		turnrate = 440,
		usepiececollisionvolumes = 1,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmVehicles/T2",
			techlevel = 2,
			unitgroup = "weaponaa",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "30 26 34",
				collisionvolumetype = "Box",
				damage = 800,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 200,
				object = "Units/armlatnk_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 80,
				object = "Units/arm2X2D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-lightning",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			armamph_missile = {
				areaofeffect = 598,
				avoidfeature = false,
				burnblow = true,
				canattackground = true,
				castshadow = true,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				craterareaofeffect = 430,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.91,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 70,
				flighttime = 44,
				-- hightrajectory = 1, --
				impulsefactor = 1.22,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				name = "Heavy a2g armor-piercing sabot missile launcher",
				noselfdamage = true,
				projectiles = 3, --
				sprayangle = 1910,
				proximitypriority = 3000,
				range = 5700,
				reloadtime = 8,
				size = 2,
				smokecolor = 0.5,
				smokeperiod = 49,
				smokesize = 14,
				smoketime = 49,
				smoketrail = true,
				smoketrailcastshadow = true,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "rocklit1",
				soundtrigger = true,
				startvelocity = 120,
				texture1 = "null",
				texture2 = "smoketrailbar",
				tolerance = 10000,
				tracks = true,
				trajectoryheight = 2, --
				turnrate = 9590,
				turret = true,
				weaponacceleration = 15,
				weapontimer = 3,
				weapontype = "MissileLauncher",
				weaponvelocity = 990,
				customparams = {
					weapons_role = "secondary",
					cruise_max_height = "4400",
					cruise_min_height = "1570",
					lockon_dist = "500",
					speceffect = "cruise",
				},
				damage = {
					vtol = 290,
					default = 158,
				},
			},
			lightning = {
				areaofeffect = 138,
				avoidfeature = false,
				beamttl = 1,
				burst = 10,
				burstrate = 0.03333,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 1,
				edgeeffectiveness = 0.45,
				energypershot = 10,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
				firestarter = 50,
				-- impactonly = 1,
				impulsefactor = 0.99,
				intensity = 24,
				name = "Close-quarters lightning turret",
				noselfdamage = true,
				-- projectiles = 3, --
				range = 900,
				reloadtime = 1.1,
				rgbcolor = "0.5 0.5 1",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				soundtrigger = true,
				thickness = 1.5,
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 600,
				customparams = {
					spark_ceg = "genericshellexplosion-splash-lightning",
					spark_forkdamage = "0.83",
					spark_maxunits = "5",
					spark_range = "120",
				},
				damage = {
					vtol = 54,
					default = 44,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "LIGHTNING",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "NOTAIR",
				def = "ARMAMPH_MISSILE",
				fastautoretargeting = true,
				onlytargetcategory = "VTOL",
			},
		},
	},
}
