return {
	armyork = {
		airsightdistance = 1700,
		buildpic = "ARMYORK.DDS",
		buildtime = 13000,
		canmove = true,
		collisionvolumeoffsets = "0 -10 -2",
		collisionvolumescales = "31 31 38",
		collisionvolumetype = "box",
		corpse = "DEAD",
		energycost = 9900,
		energystorage = 3000,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 10600,
		idleautoheal = 45,
		idletime = 300,
		leavetracks = true,
		maxacc = 0.12111,
		maxdec = 0.25223,
		maxslope = 25,
		maxwaterdepth = 55,
		metalcost = 650,
		movementclass = "TANK3",
		movestate = 0,
		nochasecategory = "NOTAIR",
		objectname = "Units/ARMYORK.s3o",
		script = "Units/ARMYORK.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 390,
		speed = 110.5,
		trackoffset = 6,
		trackstrength = 5,
		tracktype = "armyork_tracks",
		trackwidth = 33,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.63786,
		turnrate = 618.20001,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmVehicles/T2",
			shield_color_mult = 25,
			shield_power = 25400,
			shield_radius = 700,
			techlevel = 2,
			unitgroup = "aa",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -10 -2",
				collisionvolumescales = "31 31 38",
				collisionvolumetype = "box",
				damage = 1900,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 276,
				object = "Units/armyork_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 110,
				object = "Units/arm2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-flak",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "varmmove",
			},
			select = {
				[1] = "varmsel",
			},
		},
		weapondefs = {
			bogus_missile = {
				areaofeffect = 48,
				avoidfeature = false,
				canattackground = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Missiles",
				range = 1475,
				reloadtime = 0.5,
				soundhitwet = "splshbig",
				startvelocity = 450,
				tolerance = 9000,
				turnrate = 33000,
				turret = true,
				weaponacceleration = 141,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 1550,
				customparams = {
					bogus = 1,
				},
				damage = {
					default = 0,
				},
			},
			mobileflak = {
				accuracy = 500,
				areaofeffect = 340,
				avoidfeature = false,
				burnblow = true,
				canattackground = true,
				cegtag = "flaktrailaa",
				craterareaofeffect = 140,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 2,
				edgeeffectiveness = 1,
				explosiongenerator = "custom:flak",
				impulsefactor = 0.955,
				mygravity = 0.01,
				name = "Heavy g2a flak cannon",
				noselfdamage = true,
				projectiles = 3, --
				range = 1475,
				reloadtime = 0.73333,
				soundhit = "flakhit",
				soundhitwet = "splsmed",
				soundstart = "flakfire",
				stages = 0,
				turret = true,
				weaponacceleration = 141,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 1550,
				damage = {
					vtol = 200,
					default = 80,
				},
				rgbcolor = {
					[1] = 0.7,
					[2] = 0.39,
					[3] = 1,
				},
			},
			repulsor = {
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.99,
				name = "PlasmaRepulsor",
				range = 700,
				soundhitwet = "sizzle",
				weapontype = "Shield",
				damage = {
					default = 900,
				},
				shield = {
					alpha = 0.17,
					armortype = "shields",
					exterior = true,
					energyupkeep = -50,
					force = 11.5,
					intercepttype = 999,
					power = 29400,
					powerregen = 3222,
					powerregenenergy = 100,
					radius = 700,
					repulser = false,
					smart = true,
					startingpower = 22222,
					visiblerepulse = true,
					badcolor = {
						[1] = 1,
						[2] = 0.2,
						[3] = 0.2,
						[4] = 0.2,
					},
					goodcolor = {
						[1] = 0.2,
						[2] = 1,
						[3] = 0.2,
						[4] = 0.17,
					},
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
				def = "BOGUS_MISSILE",
				onlytargetcategory = "VTOL SURFACE",
			},
			[2] = {
				badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
				def = "MOBILEFLAK",
				onlytargetcategory = "VTOL SURFACE",
			},
			[3] = {
				def = "REPULSOR",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
