return {
	legafcv = {
		builddistance = 1110,
		builder = true,
		buildpic = "legafcv.DDS",
		buildtime = 4000,
		canmove = true,
		collisionvolumeoffsets = "0 -3 0",
		collisionvolumescales = "20 17 30",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 2900,
		energymake = 22,
		energystorage = 500,
		metalstorage = 500,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 3,
		footprintz = 3,
		health = 950,
		idleautoheal = 25,
		idletime = 100,
		leavetracks = true,
		maxacc = 0.07029,
		maxdec = 0.14059,
		maxslope = 22,
		maxwaterdepth = 44,
		metalcost = 200,
		movementclass = "TANK2",
		objectname = "Units/legafcv.s3o",
		script = "Units/legafcv.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 800,
		speed = 120,
		terraformspeed = 1850,
		trackoffset = 10,
		trackstrength = 5,
		tracktype = "armgremlin_tracks",
		trackwidth = 35,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.83678,
		turnrate = 635,
		workertime = 580,
		buildoptions = {
			"legwin",
			"legsolar",
			"legdrag",
			"legrad",
			"legmex",
			"leglht"
		},
		customparams = {
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Constructors",
			techlevel = 2,
			unitgroup = "buildert2",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "20 17 30",
				collisionvolumetype = "Box",
				damage = 800,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 80,
				object = "Units/legafcv_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 700,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 45,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
	},
}
