return {
	legspcarrier = {
		airsightdistance = 1350,
		maxacc = 0.18,
		activatewhenbuilt = true,
		airStrafe = false,
		blocking = true,
		bankingallowed = false,
		maxdec = 0.18,
		energycost = 5000,
		metalcost = 250,
		buildpic = "legspcarrier.DDS",
		buildtime = 9250,
		canfly = true,
		canmove = true,
		collide = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "48 14 60",
		collisionvolumetype = "Box",
		cruisealtitude = 900,
		explodeas = "largeexplosiongeneric",
		floater = true,
		footprintx = 4,
		footprintz = 4,
		hoverattack = true,
		idleautoheal = 15,
		idletime = 120,
		health = 9500,
		maxslope = 25,
		speed = 223.0,
		maxwaterdepth = 0,
		nochasecategory = "VTOL",
		objectname = "Units/legspcarrier.s3o",
		radardistance = 1450,
		script = "Units/legspcarrier.cob",
		seismicsignature = 0,
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 1200,
		turninplaceanglelimit = 360,
		turnrate = 540,
		upright = true,
		customparams = {
			unitgroup = 'weapon',
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/SeaPlanes",
			inheritxpratemultiplier = 1,
			childreninheritxp = "DRONE",
			parentsinheritxp = "DRONE",
			techlevel = 2,
			flyingcarrier = true,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
			},
			crashexplosiongenerators = {
				[1] = "crashing-large",
				[2] = "crashing-large",
				[3] = "crashing-large2",
				[4] = "crashing-large3",
				[5] = "crashing-large3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			napalmmissile = {
				areaofeffect = 425,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "burnflame-xs",
				collideenemy = false,
				collidefeature = false,
				collidefriendly = false,
				commandfire = true,
				craterareaofeffect = 360,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.75,
				energypershot = 13000,
				explosiongenerator = "custom:fire-explosion-large",
				flamegfxtime = 1,
				gravityaffected = true,
				-- mygravity = 0.05,
				-- hightrajectory = 1,
				impulseboost = 5.3, -- addedd
				impulsefactor = 5.33,
				interceptedbyshieldtype = 0,
				metalpershot = 350,
				model = "legbomb.s3o",
				name = "Long-Range Tactical Hellfire Napalm Shell",
				noselfdamage = true,
				projectiles = 3,
				sprayangle = 728,
				range = 2500,
				reloadtime = 4,
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 14.0,
				smoketime = 60,
				smoketrail = true,
				soundhit = "xplolrg4",
				soundhitwet = "splslrg",
				soundstart = "cannhvy6",
				stockpile = true,
				stockpiletime = 20,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 9000,
				turnrate = 10000,
				turret = true,
				weaponacceleration = 120,
				weapontimer = 5,
				weapontype = "Cannon",
				weaponvelocity = 550,
				customparams = {
					area_onhit_ceg = "fire-area-150-repeat",
					area_onhit_damage = 150,
					area_onhit_damageceg = "burnflamexl-gen",
					area_onhit_range = 250,
					area_onhit_resistance = "fire",
					area_onhit_time = 25,
					stockpilelimit = 20,
				},
				damage = {
					commanders = 700,
					default = 2200, -- with area damage, 3000, minus some self-interference, so about 2750
				},
			},
			leg_drone_controller = {
				areaofeffect = 4,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				gravityaffected = "true",
				hightrajectory = 1,
				impulsefactor = 0.123,
				name = "Drone Targeting System",
				noselfdamage = true,
				metalpershot = 15,
				energypershot = 500,
				range = 1200,
				reloadtime = 2.5,
				size = 0,
				soundhit = "",
				soundhitwet = "",
				soundstart = "",
				stockpile = true,
				stockpiletime = 10,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				damage = {
					default = 0,
				},
				customparams = {
					carried_unit = "legdrone",     --Name of the unit spawned by this carrier unit.
					engagementrange = 1300,
					-- spawns_surface = "SEA",    -- "LAND" or "SEA". The SEA option has not been tested currently.
					spawnrate = 5, 				--Spawnrate roughly in seconds.
					maxunits = 7,				--Will spawn units until this amount has been reached.
					energycost = 500,			--Custom spawn cost. Remove this or set = nil to inherit the cost from the carried_unit unitDef. Cost inheritance is currently not working.
					metalcost = 15,				--Custom spawn cost. Remove this or set = nil to inherit the cost from the carried_unit unitDef. Cost inheritance is currently not working.
					controlradius = 1400,			--The spawned units should stay within this radius. Unfinished behavior may cause exceptions. Planned: radius = 0 to disable radius limit.
					decayrate = 4,
					carrierdeaththroe = "release",
					dockingarmor = 0.2,
					dockinghealrate = 24,
					docktohealthreshold = 66,
					enabledocking = true,		--If enabled, docking behavior is used. Currently docking while moving or stopping, and undocking while attacking. Unfinished behavior may cause exceptions.
					dockingHelperSpeed = 5,
					dockingpieces = "11 13",
					dockingradius = 100,			--The range at which the units snap to the carrier unit when docking.
					stockpilelimit = 7,
					stockpilemetal = 15,
					stockpileenergy = 500,
					dronesusestockpile = true,
					-- cobdockparam = 1,
					-- cobundockparam = 1,
				}
			},
		},
		weapons = {
			[1] = {
				-- badtargetcategory = "VTOL",
				def = "leg_drone_controller",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "napalmmissile",
				maindir = "0 0 1",
				maxangledif = 240,
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
