return {
	legctl = {
		activatewhenbuilt = true,
		buildangle = 16384,
		buildpic = "legctl.DDS",
		buildtime = 5900,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "38 46 40",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 2200,
		explodeas = "smallBuildingExplosionGeneric",
		footprintx = 4,
		footprintz = 4,
		health = 2200,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 28,
		maxwaterdepth = 0,
		metalcost = 240,
		objectname = "Units/legctl.s3o",
		script = "Units/legctl.cob",
		radardistance = 1500,
		seismicsignature = 0,
		selfdestructas = "smallBuildingExplosionGenericSelfd",
		sightdistance = 917,
		sonardistance = 1600,
		yardmap = "ooooooooo",
		customparams = {
			-- buildinggrounddecaldecayspeed = 30,
			-- buildinggrounddecalsizex = 4,
			-- buildinggrounddecalsizey = 4,
			-- buildinggrounddecaltype = "decals/armdl_aoplane.dds",
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removewait = true,
			subfolder = "Legion/SeaDefenses",
			unitgroup = "sub",
			-- usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "38 46 40",
				collisionvolumetype = "Box",
				damage = 609,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 30,
				metal = 176,
				object = "Units/legctl_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 305,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 70,
				object = "Units/arm3X3C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servmed2",
			},
			select = {
				[1] = "servmed2",
			},
		},
		weapondefs = {
			torplauncher = {
				areaofeffect = 720,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				bouncerebound = 0.79,
				bounceslip = 0.6,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				flighttime = 20.75,
				gravityaffected = "true",
				groundbounce = true,
				--hightrajectory = 1,
				impulsefactor = 3.123,
				model = "legbasictorpedo.s3o",
				mygravity = 0.11,
				name = "Homing Torpedo Launcher",
				noselfdamage = true,
				numbounce = 1,
				predictboost = 1,
				range = 4600,
				reloadtime = 3.5,
				soundhit = "xplodep2",
				soundhitvolume = 3,
				soundhitwet = "splsmed",
				soundhitwetvolume = 12,
				soundstart = "torpedo1",
				startvelocity = 220,
				tracks = true,
				trajectoryheight = 2,
				projectiles = 5,
				sprayangle = 100,
				turnrate = 64000,
				turret = true,
				waterweapon = true,
				weaponacceleration = 125,
				weapontype = "Cannon",
				weaponvelocity = 600,
				damage = {
					default = 425,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "torplauncher",
				onlytargetcategory = "NOTHOVER SURFACE",
			},
		},
	},
}
